### ISSUE TITLE
Deserialization of restorationjob's patch.json fails to deserialize namespace value

### ISSUE THREAD

**Issue by markphillips100** [Azure/Bridge-To-Kubernetes#113]
**Describe the bug**
The restorationjob fails to deserialize the namespace value contained within the patch.json file causing a null namespace to be passed to `ReadNamespacedDeploymentWithHttpMessagesAsync` which throws an ArgumentNullException.

**Mention the platform you are using**
Windows 11, VS2022, Kubernetes KinD cluster v1.23.5

**To Reproduce**
Install VS2022 B2K extension, F5 a project, connect to cluster.
Restorationjob pod starts, exceptions and CrashLoopBackoffs.
404 always returned from previous working browser url.

**Expected behavior**
Should not exception, but no idea beyond that as not got any further.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Here's the pod log from restoration job:
```
at k8s.AbstractKubernetes.ReadNamespacedDeploymentWithHttpMessagesAsync(String name, String namespaceParameter, Nullable`1 pretty, IReadOnlyDictionary`2 customHeaders, CancellationToken cancellationToken)

at k8s.KubernetesExtensions.ReadNamespacedDeploymentAsync(IBasicKubernetes operations, String name, String namespaceParameter, Nullable`1 pretty, CancellationToken cancellationToken)

at Microsoft.BridgeToKubernetes.Common.Kubernetes.KubernetesClient.<>c__DisplayClass63_0.<<GetV1DeploymentAsync>b__0>d.MoveNext() in /src/common/Kubernetes/KubernetesClient.cs:line 683

--- End of stack trace from previous location where exception was thrown ---

at Microsoft.BridgeToKubernetes.Common.Kubernetes.KubernetesClient.<>c__DisplayClass75_0`1.<<ClientInvokeWrapperAsync>b__0>d.MoveNext() in /src/common/Kubernetes/KubernetesClient.cs:line 1058

--- End of stack trace from previous location where exception was thrown ---

at Microsoft.BridgeToKubernetes.Common.Utilities.WebUtilities.RetryUntilTimeAsync(Func`2 action, TimeSpan maxWaitTime, CancellationToken cancellationToken) in /src/common/Utilities/WebUtilities.cs:line 112

at Microsoft.BridgeToKubernetes.Common.Kubernetes.KubernetesClient.ClientInvokeWrapperAsync[T](Func`1 handler, String operation, CancellationToken cancellationToken) in /src/common/Kubernetes/KubernetesClient.cs:line 1054

at Microsoft.BridgeToKubernetes.Common.Kubernetes.KubernetesClient.<>c__DisplayClass24_0.<<ListPodsForDeploymentAsync>b__0>d.MoveNext() in /src/common/Kubernetes/KubernetesClient.cs:line 202

--- End of stack trace from previous location where exception was thrown ---

at Microsoft.BridgeToKubernetes.Common.Kubernetes.KubernetesClient.<>c__DisplayClass75_0`1.<<ClientInvokeWrapperAsync>b__0>d.MoveNext() in /src/common/Kubernetes/KubernetesClient.cs:line 1058

--- End of stack trace from previous location where exception was thrown ---

at Microsoft.BridgeToKubernetes.Common.Utilities.WebUtilities.RetryUntilTimeAsync(Func`2 action, TimeSpan maxWaitTime, CancellationToken cancellationToken) in /src/common/Utilities/WebUtilities.cs:line 112

at Microsoft.BridgeToKubernetes.Common.Kubernetes.KubernetesClient.ClientInvokeWrapperAsync[T](Func`1 handler, String operation, CancellationToken cancellationToken) in /src/common/Kubernetes/KubernetesClient.cs:line 1054

at Microsoft.BridgeToKubernetes.DevHostAgent.RestorationJob.RestorationJobApp._GetAgentEndpointAsync(DeploymentPatch deploymentPatch, CancellationToken cancellationToken) in /src/devhostagent.restorationjob/RestorationJobApp.cs:line 236","RemoteStackTraceString

```

I wrote a small unit test to confirm suspicions around using Newtonsoft.Json rather than System.Text.Json.  This just uses the current DeploymentPatch.json file in the devhostAgent.restorationjob.tests:
```
        [Fact]
        public void EnsureCanDeserializePatch()
        {
            string patchStateJson = File.ReadAllText(Path.Combine("TestData", "DeploymentPatch.json"));
            var deploymentPatch = JsonHelpers.DeserializeObject<DeploymentPatch>(patchStateJson);

            string name = deploymentPatch.Deployment.Name();
            string ns = deploymentPatch.Deployment.Namespace();

            Assert.Equal("bikes", name);
            Assert.Equal("dev", ns);
        }
```

The test fails as the ns variable is null.  The reason being the generated k8s.Models.V1ObjectMeta type's NamespaceProperty only supports a System.Text.Json.JsonPropertyName attribute so Newtonsoft.Json will not know to deserialize from the "namespace" name.  There are many other type properties with this attribute but their name only differs by case whereas this one differs by more than case alone.

**Comment by Eneuman** [comment]
We have the same problem and it makes using B2K unbearble :(
This realy needs to get some attention and get fixed.

**Comment by markphillips100** [comment]
The correct deserialization can at least be resolved by implementation of a custom contract resolver to check for the STJ attribute and return it's name value:

```
    internal class STJContractResolver : CamelCasePropertyNamesContractResolver
    {
        protected override JsonProperty CreateProperty(MemberInfo member, MemberSerialization memberSerialization)
        {
            JsonProperty property = base.CreateProperty(member, memberSerialization);

            if (member.GetCustomAttribute<JsonPropertyNameAttribute>() is { } stj)
            {
                property.PropertyName = stj.Name;
                return property;
            }

            return property;
        }
    }
```

This allows the unit test in the OP to pass.  I've no way of testing it in a wider context of the restoration job, dsc CLI, and the IDE extensions, but I suspect this would prevent the `ReadNamespacedDeploymentWithHttpMessagesAsync` from throwing the ArgumentNullException and at least progress further.

**Comment by markphillips100** [comment]
I managed to get some success with a few changes and observations others might be affected by.  All this testing was with isolated mode unchecked.

Firstly, I applied the STJContractResolver wherever a contract resolver was used.  To use the new code I built 2 new images to replace the `lpkrestorationjob` and `lpkremoteagent` images.  As a side issue, there were 2 issues building these:

1. The shebang [here](https://github.com/Azure/Bridge-To-Kubernetes/blob/9b82b5b47a24f4ec5d4d6eaa4d2610eb0dadde74/build/setup-alpine-tools.sh#L1) has a spelling error.
2. Bash is not installed on the base image used so had to change the shebang line to use sh instead of bash.

Images were built, pushed to my cluster's private registry, and env var overrides set for BRIDGE_DEVHOSTIMAGENAME and BRIDGE_RESTORATIONJOBIMAGENAME.  F5 and restoration job no longer throws the ArgumentNullException.

All was not good though.  If I check the logs of the agent pod when F5 is running I would only see the initial kestrel UseUrls statement and no other log data.  This implied (to me) that no communication was happening from either the restorationjob pod or the localhost.  Sure enough the restorationjob had a few connection refused entries now.

Turns out I had been using kestrel's configuration way of specifying the urls to use, as described [here](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel/endpoints?view=aspnetcore-7.0#configureiconfiguration).  I had an env var `Kestrel__Endpoints__Http__Url` set to `http://*:80`.

It seems doing this forces kestrel to ignore what the devhostagent's UseUrls was specifying, namely 50051.  This may be behaviour unique to netcoreapp3.1 as used by the remote agent. Regardless, and to get things working, I switched the env var used by my app to ASPNETCORE_URLS instead.  This allowed the agent to be communicated with from the restorationjob's pings and the localhost's channel setup for port forwarding.  I was able to terminal into the remote agent and `netstat -nltp` revealed both my original port 80 and the new 50051.

As a suggestion, probably worth mentioning this small detail in some troubleshooting guide?

I have other issues related to the app I'm debugging not receiving data being forwarded by the agent that results in 502 in client app.  I'm fairly positive these are issues with my app though as I created a new web app to use as a replacement for the remote app being debugged and urls and debugging work fine.

**Comment by markphillips100** [comment]
FYI my 502 issue was also due to a local appsettings.json specifying the kestrel urls.  Removed that and just used "applicationUrls" in launchsettings.json and debugging is working wonderfully.

So aside from that it really comes down to newtonsoft and STJ contract misalignment.  Are there any plans to move over to STJ or are there other reasons for continuing with Newtonsoft?  And I mean that in a broader context of migration towards .net6/7.

**Comment by elenavillamil** [comment]
Hi @markphillips100, thank you very much for the detail issue and investigation. If you have a working change to remediate this issue, we would greatly appreciate if you could send a PR with your changes. We will review and have our testing run some integration and regression testing on it.

Here is some background: when we upgraded C# KubernetesClient API version it introduced some pain with Json serialization and deserialization. The new version of C# KubernetsClient API switches from using newtonsoft to System.Text.Json and that introduced serialization breaking changes. We explore changing our own code to use System.Text.Json but it is missing native json path support and changes to make it work were extensive. We ended up adding setting to force CamelCase, but missed this case where some attributes differ by more than just casing.

**Comment by markphillips100** [comment]
@elenavillamil totally understand not moving to STJ due to the limitations in regards to patching.  It was just a thought, and to be honest really doesn't impact a consumer of the tool.

I shall try and submit a PR early next week.

**Comment by Eneuman** [comment]
@elenavillamil Any ETA when will be released?

**Comment by elenavillamil** [comment]
@Eneuman and @markphillips100, sorry for the delay. The teams was focused on dotnet6 change and testing which delayed this. We started testing for this PR a couple weeks ago, our testing team reported an issue on restore job when using this build. We are working on investigating this next. We will keep this issue updated with findings.

**Comment by markphillips100** [comment]
FYI, I'm still using my original build and have been for some time with no issues.  It's possible the recent merges for dotnet 6 introduced some issue not affecting me.

**Comment by elenavillamil** [comment]
You should be able to repo if you follow steps here: https://github.com/Azure/Bridge-To-Kubernetes/blob/main/tests/manual/BridgeToKubernetes.md#k8s-integration (this is using todo-app sample app in samples folder of this repo). Before the change this sample ran fine, now we see the ReadNamespacedDeploymentWithHttpMessagesAsync exception you mentioned above. I am currently debugging to try to understand why. You should be able to repo this with your current dotnet3.1 build as well. But please let me know if you cant repo with your current build.

**Comment by elenavillamil** [comment]
It was an issue on our end. Checking of the latest PR had overriden the docker images on the dev environment. I have fixed it and asked testing team to validate again.
