### ISSUE TITLE
Unable to call Kubernetes API endpoint from local process when B2K running

### ISSUE THREAD

**Issue by markphillips100** [Azure/Bridge-To-Kubernetes#115]
**Describe the bug**
I'm unable to make http requests to the k8 API endpoint from my B2K local process, specifically for listing some CRD instances.  This works fine with the app under normal cluster conditions but when launching B2K the local process reports that my kubeclient (nothing to do with B2K's) is unable to connect to the API endpoint:
```
A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
```

I have a KubernetesLocalProcessConfig.yaml defined to copy the pod's kube-api-access-* volume details:
```
version: 0.1
env:
  - name: KUBERNETES_SERVICE_ACCOUNT_PATH_OVERRIDE
    value: $(volumeMounts:kube-api-access-*)
```
And I use the env var override when creating my kubeclient.

Is there something else I need to do to allow the local process access to the https://x.x.x.x:443/ API endpoint?

**Mention the platform you are using**
VS2022 + B2K extension

**Expected behavior**
The local process should be able to communicate with the cluster IP API server endpoint to query resources, as long as the pod's service account rbac supports it.

**Desktop (please complete the following information):**
Windows 11, WSL2 + Ubuntu 22.04

**Comment by markphillips100** [comment]
Sure thing @hsubramanianaks.  I'm not seeing any log statements in relation to the http request I am making though.

My pod makes use of a different [kubeclient](https://www.nuget.org/packages/KubeClient.Extensions.DependencyInjection) to yours for querying some CRDs using the kubernetes API.  This works when inside the cluster.  Necessary role bindings setup to support access to the required CRDs.

During B2K operation the mapped kube-api-access volume is loaded by the kubeclient successfully (I debugged thanks to B2K :-) ) so the subsequent http request attempted is configured for the cluster internal IP and port and has the required token too.

It sort of makes sense that whilst B2K is running my localhost process would not be able to access the API server IP.  I assume it would be necessary for the endpoint manager (or something) to forward traffic into the cluster for this IP and port (443), much like it can do for other services running in the cluster?  If that's the case, is it possible currently to do that, or perhaps it's something that should just happen anyway, maybe via a feature switch?

[bridge-library-2022-11-29-22-28-14-26052.txt](https://github.com/Azure/Bridge-To-Kubernetes/files/10118006/bridge-library-2022-11-29-22-28-14-26052.txt)
[bridge-endpointmanager-2022-11-29-22-24-22-20152.txt](https://github.com/Azure/Bridge-To-Kubernetes/files/10118007/bridge-endpointmanager-2022-11-29-22-24-22-20152.txt)

**Comment by markphillips100** [comment]
I can get around the issue by specifying (my) KubeClient's environment overrides in the KubernetesLocalProcessConfig, namely KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT.  It requires me to run a kubectl proxy for the apiserver access, so I use a well defined port number to save changing it each time.  

Would be nice to have B2K automate the proxy part of the configuration via some feature if possible.  The host and port are well known env vars for kubernetes (I think) so should work in all clusters.  The volume mount for token access is likely kube client specific, from an environment perspective, so would not expect that to be a built-in feature.

Just for completeness, I start the proxy using `kubectl proxy --port=59000` and specify the following in the yaml:
```
version: 0.1
env:
  - name: KUBERNETES_SERVICE_ACCOUNT_PATH_OVERRIDE
    value: $(volumeMounts:kube-api-access-*)
  - name: KUBERNETES_SERVICE_HOST
    value: "127.0.0.1"
  - name: KUBERNETES_SERVICE_PORT # Must start a kubectl proxy --port=59000
    value: "59000"
```

**Comment by elenavillamil** [comment]
@markphillips100, have you checked [this doc](https://learn.microsoft.com/en-us/visualstudio/bridge/configure-bridge-to-kubernetes) under "Make a Service Available" section? I am pretty sure if you service needs to talk to kubernetes API adding below will work. It will get bridge to automatically add your KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT environment variables.

Example of what to add to your KubernetesLocalProcessConfig.yaml
_- name: KUBERNETES_SVC
    value: $(services:kubernetes.default)_

**Comment by markphillips100** [comment]
@elenavillamil ah that might work.  I'll try it soon.  Totally forgot I could access the kubeapi via the service.

**Comment by elenavillamil** [comment]
@markphillips100 we are closing this issue. If above does not solve your problem please feel free to re-open :)
