### ISSUE TITLE
Remote Debugging in Bridge to Kubernetes: Is this a feature you would like to see?

### ISSUE THREAD

**Issue by qpetraroia** [Azure/Bridge-To-Kubernetes#116]
Hi everyone, 

I want to start a conversation here to see if folks would be interested having the possibility of remote debugging in Bridge to Kubernetes. If you are curious to learn more about remote debugging this [doc](https://learn.microsoft.com/visualstudio/debugger/remote-debugging-azure?view=vs-2022) explains how to set up and configure a Visual Studio ASP.NET Core app, deploy it to IIS using an Azure VM, and attach the remote debugger from Visual Studio. 

Please feel free to leave a comment if remote debugging is something that you would like to see in Bridge.

Thank you!

**Comment by markphillips100** [comment]
I think it would be nice to have a single way across both VS2022 and VSCode to do both F5 (local debugging) and Attach (remote debugging).

In lieu of a good F5 experience for non-AKS clusters (until recently) I've been using an attach to remote process from VSCode for a while, and only recently a similar experience in VS2022 using a custom Marketplace extension for remote debugging.

Both require me to install vsdbg into my docker images first so this is kinda a dev-only thing.  Not sure if there's another way but would be nice for Bridge to sort out the install of the debugger for you.  In addition, a custom bash script is configured locally as part of the attach step to facilitate the spin-up of the vsdbg on the specific pod in the required namespace.

With Sourcelink configured too this works as a debug-existing-container experience but would be nice just to have that B2K experience builtin.

**Comment by elenavillamil** [comment]
We are closing this one for right now as it does not seems there is a lot of interest on it. We can always re-open later on if needed. Thank you everyone!
