### ISSUE TITLE
Not able to connect Mysql Service from B2K

### ISSUE THREAD

**Issue by Pawangi-t** [Azure/Bridge-To-Kubernetes#128]
Hi, 

I am redirecting (AMF ) one of the services from K8 cluster to B2K which is running on VS2022.This pod is connecting to  Mysql service running in the cluster and it is using service name of Mysql as host name in its connection string. 

**Issue**: AMF pod  is not able to connect Mysql service when runs in B2K , however with same credentials it is well connecting within K8 cluster.

**OS of B2K machine**: Windows 11 Pro
**K8 Cluster:**  Ubuntu 20.04 VBoxes with one Master and one worker node. 

  ### Exception is B2K:
![image](https://user-images.githubusercontent.com/88675187/206970469-766b3cfd-ae5b-43db-8bdf-096b7414b37b.png)
![image](https://user-images.githubusercontent.com/88675187/206970519-5d80b834-ff0a-458f-ad57-107cc551a7da.png)

Please let me know if more details are required.

Thanks

**Comment by hsubramanianaks** [comment]
@Pawangi-t Thank you for raising this issue. Can you share your logs for B2K from C:\Users\..\AppData\Local\Temp\Bridge To Kubernetes ? We can look further into it once we have received the logs.

**Comment by elenavillamil** [comment]
@Pawangi-t we are closing this issue due to lack of inactivity. Please feel free to re-open if needed.
