### ISSUE TITLE
useKubernetesServiceEnvironmentVariables requires admin privileges in VS extension

### ISSUE THREAD

**Issue by twsouthwick** [Azure/Bridge-To-Kubernetes#131]
I'm running the Bridge to Kubernetes on both VS Code and VS. I have been able to get useKubernetesServiceEnvironmentVariables to work in VS Code where it won't attempt to update the host files by setting the following:

```json
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "bridge-to-kubernetes.resource",
            "type": "bridge-to-kubernetes.resource",
            "resource": "stats-api",
            "resourceType": "service",
            "ports": [
                3001
            ],
            "targetCluster": "minikube",
            "targetNamespace": "todo-app",
            "useKubernetesServiceEnvironmentVariables": true,
        }
    ]
}
```

However, I haven't figured out where to set this in VS. I've tried adding it to the launchSettings.json where the launch command is added but it still attempts to update the host file:

```json
{
  "profiles": {
    "http": {
      "commandName": "Project",
      "launchBrowser": true,
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      },
      "dotnetRunMessages": true,
      "applicationUrl": "http://localhost:3001"
    },
    "https": {
      "commandName": "Project",
      "launchBrowser": true,
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      },
      "dotnetRunMessages": true,
      "applicationUrl": "https://localhost:7145;http://localhost:3001"
    },
    "IIS Express": {
      "commandName": "IISExpress",
      "launchBrowser": true,
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    },
    "Bridge to Kubernetes": {
      "commandName": "AzureDevSpacesLocal",
      "launchBrowser": true,
      "useKubernetesServiceEnvironmentVariables": true
    }
  },
  "iisSettings": {
    "windowsAuthentication": false,
    "anonymousAuthentication": true,
    "iisExpress": {
      "applicationUrl": "http://localhost:3001",
      "sslPort": 44303
    }
  }
}
```

**Expected behavior**
I expect to be able to set this flag according to https://learn.microsoft.com/en-us/visualstudio/bridge/kubernetes-environment-variables so I don't have to elevate to admin while running

**Desktop (please complete the following information):**
 - OS: Windows 22621.963
 - VS Version: 17.4.2
 - VS Extension version: 0.1

**Comment by hsubramanianaks** [comment]
Thanks for raising this issue, the variable name is different for VS extension it is "useKubeServiceEnvironmentVariables":  true in launchsettings.json. we will work internally to update documentation. 

![image](https://user-images.githubusercontent.com/105889062/208752251-97139f2f-ce5a-41a3-a557-49ddf6942b7d.png)

**Comment by twsouthwick** [comment]
Is the plan to update the extension to use the same name or to update the docs?

**Comment by hsubramanianaks** [comment]
@twsouthwick we are planning to update the docs. Thank you. @sabbour FYI

**Comment by elenavillamil** [comment]
We will also explore updating VS extension to use same setting name for better usability.

**Comment by elenavillamil** [comment]
Closing this issue. Since 0216 release name is now the same between VSCode and VS :)
