### ISSUE TITLE
EndpointManagerTest "AddHostsFileEntry" does not work as intended

### ISSUE THREAD

**Issue by Eneuman** [Azure/Bridge-To-Kubernetes#135]
In this line it says that `EndpointManagerRequest<T>` where `T is a IEnumerable<HostsFileEntry>`.

https://github.com/Azure/Bridge-To-Kubernetes/blob/7bdf7384b3eb0707d59a75a3276e037e332ae2c7/src/endpointmanager.tests/EndpointManagerTests.cs#L41

Looking at the code that this test should cover:
https://github.com/Azure/Bridge-To-Kubernetes/blob/7bdf7384b3eb0707d59a75a3276e037e332ae2c7/src/endpointmanager/EndpointManager.cs#L244

T should be a tuplet of` (string workloadNamespace, IEnumerable<HostsFileEntry> entries)`.
Yet, this test passes.

When switching to System.Text.Json this test failes.

**Comment by Eneuman** [comment]
Since System.Text.Json is not very good att handling Tuplets (alot of extra work will be needed with custom convert etc), I would suggest replacing the tuplet with a new "AddHostsFileEntry" object and use that as T

**Comment by elenavillamil** [comment]
The suggestion sounds good. We will discuss with the team on our next weekly sync and update here. Thank you very much for contributing to make bridge better!

**Comment by hsubramanianaks** [comment]
This is handled in this huge PR - https://github.com/Azure/Bridge-To-Kubernetes/pull/153.
