### ISSUE TITLE
Bridge End to End Integration Tests

### ISSUE THREAD

**Issue by elenavillamil** [Azure/Bridge-To-Kubernetes#140]
Today Bridge only has UTs. All integration test is done manually. With this feature we will add integration test coverage that is automated and runs with every PR. 

General idea of how this can be accomplished: Set up a pipeline that runs following tasks:
* Create test cluster
* Deploy todo app
* Connect bridge to stats-api, and verify connect happened successfully
* Add todo item using frontend url
* Go to stats-api link and validate correct entries returned.

**Comment by hsubramanianaks** [comment]
I like this idea; it reduces the load on testing team. I was talking about this with Joyer last night. Suggested looking for tools like cypress, playwright to automate it or write a script to test them as CLI. there are several ways to accomplish this. Thank you for raising this enhancement request. @GatoonJin  FYI.

**Comment by elenavillamil** [comment]
@hsubramanianaks assigned this to you since you started looking into it. Look forward to see what you come up with :)

**Comment by hsubramanianaks** [comment]
we have live tests here for linux, similar needs to be done with windows and macos. One restriction is installing minikube or kind clusters in windows/macos runner are tough and causes issues. Only other way is to create an AKS cluster under testing subscription and use that cluster for live automated tests. @cxznmhdcxz FYI.

**Comment by hsubramanianaks** [comment]
@cxznmhdcxz As discussed can you add more complex tests to these live tests and make them parallel? Today it checks out the projects, setups cluster and runs b2k connect (basic testing). But do we want to enhance this live testing experience to more use cases like test routing, ingress, managed identity, dapr etc.. Thank you.

**Comment by hsubramanianaks** [comment]
Closing this as this was completed by Ruijun.
