### ISSUE TITLE
[FEEDBACK]

### ISSUE THREAD

**Issue by cheburakshu** [Azure/Bridge-To-Kubernetes#142]
> With this workflow, there is no need for extra assets, such as a Dockerfile or Kubernetes manifests. You can simply run your code natively on your development workstation while connected to the Kubernetes cluster

With all due respect, please revisit this assertion. A lot of developers would simply re-use the container that is already used for the devops lifecycle. If they already have a container why force them to build a native env with all the crappy virtualization tools?

**Comment by elenavillamil** [comment]
@cheburakshu thank you for your feedback. We are happy to update our documentation to improve it. Maybe you have some suggestion on how to reword it? Bridge targets the case where user wants to run locally so they can take advantage of debugging tools such as VSCode and Visual Studio. Are you saying you can still take advantage of bridge by using the devops container instead of setting up your environment locally? If so, maybe you can provide some more details on how?

**Comment by cheburakshu** [comment]
Think about my use case:

I am running a hello service in my local kubernetes cluster with Google's `skaffold` that I am using for local deployment and debugging using vscode. In short, I am already having a service accessible at http://localhost:8080 (if 8080 is the port that is the service is running on).

Now I deploy the same service to some remote cluster. I want to debug this one. I use B2K to redirect the traffic to my local computer. 

At this point, the documentation tries to say, no need to any docker, virtualization tools etc and wants another instance of service running locally. This is counter intuitive. If there is already a service running on the local computer that can accept the incoming traffic, can B2K just interface with the running service.

For egress traffic back to remote cluster from the local service, you are already making changes to /etc/hosts file to resolve the service names to ips of remote cluster. Further, if the customer is running a proxy like envoy, even changing the /etc/hosts can be avoided, and envoy is smart enough to route traffic.

I know this is not the intent of the documentation, as this is not even how B2K works today, but I just tried to answer this

> Are you saying you can still take advantage of bridge by using the devops container instead of setting up your environment locally? If so, maybe you can provide some more details on how?

**Comment by sabbour** [comment]
@cheburakshu sure, if you already have a local Kubernetes cluster and you're able to run your specific microservice and all its possible dependencies locally (other microservices, databases, service bus queues, etc.) then perhaps Bridge to Kubernetes isn't really a suitable solution for this scenario. Bridge to Kubernetes is designed to address the situation where there are multiple developers who want to test their changes against a central "integration" Kubernetes cluster without having to clone all other changes and dependencies locally. It allows you to quickly run your code locally without having to build it into a container first while still connected to the context of the larger application.

**Comment by cheburakshu** [comment]
> local Kubernetes cluster and you're able to run your specific microservice and all its possible dependencies locally (other microservices, databases, service bus queues, etc.) 
I never said I want to run all possible dependencies of a micro-service. I only said, I have a given micro service running in a cluster that can accept traffic at the given port just as a non-containerized service can. Why differentiate between a service that is running in a container and one that isn't?

**Comment by sabbour** [comment]
Thank you so much for reaching out. Looping back to better understand this use case scenario and to enable the Bridge to Kubernetes experience to progressively improve. 

Is the feedback mainly about wording in the documentation, or is there a specifc scenario that you're trying to use Bridge to Kubernetes in but you're unable to? We're happy to look at feature requests to triage and get thoughts on how we can add this in current workflow for this tool.

Thank you so much for being this feedback, really appreciate you time and discussion.

**Comment by cheburakshu** [comment]
Thanks @sabbour. Not really docs, but as a general feedback, the assertion that you can do away with all of virtualization tools is kind of backwards.
With regard to feature, I would have liked if it would work with an already containerized service. Seems this is targeted for services like Java where there is JVM, which won't work my use case. Anyway, thanks for the prompt response. Feel free to close this issue 👍
