### ISSUE TITLE
Saved cloned pod is not cleaned from added env variables

### ISSUE THREAD

**Issue by Eneuman** [Azure/Bridge-To-Kubernetes#147]
When a pod is cloned, a backup of the pod spec is saved and  b2k env variables are added to the agent pod.
If b2k craches, thoose added env variables are not removed and no check if beeing made if they already exists before adding them.

This leeds to this:
![image](https://user-images.githubusercontent.com/12099277/212539223-3cf2c23b-878e-4565-aa44-5840befec168.png)

I suggest adding code to clean the saved pod spec from any added env variables.
This will make sure that the env variable only exists once.

Code could be added here:
https://github.com/Azure/Bridge-To-Kubernetes/blob/991c6a393f31fa581258f598b9a2dd1410a0a9f6/src/library/Connect/KubernetesRemoteEnvironmentManager.cs#L632

**Comment by Vidya2606** [comment]
Hi @Eneuman can you please provide the steps to reproduce the issue ? When the bridge crashes how are you restoring it?

**Comment by Eneuman** [comment]
@Vidya2606 Sure
Have a pod that contain probes running in your AKS.
Start debugging you local service.
Keep looking at your pods using k9s or something like that. The restore agents should crash and restart after 12 failed pings. When it do I think it uses the saved patch document and applies that, hence creating multiple instances of the env variables each time it restarts.

I haven't confirmed that's the case but my guess is the calls to DeplyPatchV1Async is causing this to happen.

**Comment by hsubramanianaks** [comment]
This is released with version 1.0.20230418.1. Closing the issue.
