### ISSUE TITLE
Add winget support for windows CLI

### ISSUE THREAD

**Issue by giulianob** [Azure/Bridge-To-Kubernetes#156]
I would like to install the CLI in Windows via `winget`. The docs says the CLI only works on Windows via WSL but after inspecting the install script I see there is a Windows build that works great. Would it be possible to add `winget` support so it's easy to install?

**Comment by hsubramanianaks** [comment]
@giulianob Thanks for raising this request. you can also use it via git bash, read me documentation has links to it. we can definitely add winget support if more users need them, plus we will discuss internally to see how feasible this will be technically. Thanks again.

**Comment by hsubramanianaks** [comment]
@giulianob Please feel free to reopen this issue if you think you need this feature. Thank you.

**Comment by penenkel** [comment]
I would also like this feature.
