### ISSUE TITLE
Breakpoints not being hit despite showing as loaded

### ISSUE THREAD

**Issue by tophallen** [Azure/Bridge-To-Kubernetes#160]
**Describe the bug**
I have multiple dapr services in my minikube cluster on my local machine, when I try to attach to any one of them and set breakpoints, the breakpoints load, but they are never hit. The log files don't seem to suggest a critical errors, but I'm not 100% sure since there is a lot of trace statements.

I'm not sure if I have something set up wrong, or if it is truly broken.

**Mention the platform you are using**
I have attempted this in both Visual Studio Enterprise 2022 17.4.4 and VS Code 1.71.0

**To Reproduce**
1. Have deployed dapr services in minikube
2. configure bridge to kubernetes to point at the desired service for the respective project (build and deployed in debug mode)
3. set breakpoints
4. start debugging
5. call service via ingress

**Expected behavior**
I would expect it to hit a break point of any sort, whether on service restart or on API call.

**Screenshots**
minikube details

![services](https://user-images.githubusercontent.com/2038465/216728957-a30fe43a-947d-410a-9427-3fe90e8731f6.png)
![pods](https://user-images.githubusercontent.com/2038465/216729013-063a84fa-cef7-4265-905c-2365b7d61942.png)
![replicas and deployments](https://user-images.githubusercontent.com/2038465/216729034-74dc37ad-648b-45ef-8e14-1666a7c805d9.png)

**Desktop (please complete the following information):**
- OS: Windows 10 Enterprise
- Build: 22H2 19045.2486
- minikube version: 1.28.0
- kubctl version:
  - Client Version: v1.25.2
  - Kustomize Version: v4.5.7
  - Server Version: v1.25.3

**Additional context**

I have all my services setup as .NET 6 AspNetCore services, all using a self-signed certificate the aspnet listeners
the service templating-api (and templating-api-dapr) is set up as a ingress service with a RESTful http api, the other services are using dapr service invocation and gRPC as the protocol.

- [logs.zip](https://github.com/Azure/Bridge-To-Kubernetes/files/10583505/logs.zip)
- [VS2022-info.txt](https://github.com/Azure/Bridge-To-Kubernetes/files/10583506/VS2022-info.txt)

VS Code details:

- Version: 1.71.0 (user setup)
- Commit: 784b0177c56c607789f9638da7b6bf3230d47a8c
- Date: 2022-09-01T07:36:10.600Z
- Electron: 19.0.12
- Chromium: 102.0.5005.167
- Node.js: 16.14.2
- V8: 10.2.154.15-electron.0
- OS: Windows_NT x64 10.0.19045
- Sandboxed: No

**Comment by elenavillamil** [comment]
Hi @tophallen, thank you for all the details on the issue :) This scenario should work. I looked at the logs and I noticed bridge displayed below warning. Have you tired stopping that service using port 80 and trying without port 80 being taken? 
{"serviceMessages":[{"ports":[80],"message":"Service 'World Wide Web Publishing Service' is taking common port(s) '80' on your machine and may prevent 'Bridge To Kubernetes' from forwarding network traffic. Please stop this service and try again."}],"portBinding":{"135":"PID 1232 RpcSs [svchost.exe]","445":"PID 4

**Comment by tophallen** [comment]
@elenavillamil Thanks, that ended up being the cause of the issue for debugging in VS Code, I was able to successfully hit breakpoints. Didn't realize 80 in a pod would block the bridge. Are there any plans to make that port editable?

That ingress service `templating-api` was using both 443 and 80, removed 80 and that seems to have solved it.

In VS2022 I am getting 500 errors however `transport: authentication handshake failed: tls: first record does not look like a TLS handshake` in the application logs and `Error: write EPROTO 64146440:error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER:../../../../src/third_party/boringssl/src/ssl/tls_record.cc:242` in Postman when I try to call the endpoint.

Not sure if that is an issue with Bridge to kubernetes or not, the visual studio extension seems to have more limitations than VS Code currently. 

As long as I can debug my local cluster I am happy. :) let me know if logs for that visual studio issue seem useful, otherwise my primary issue is resolved.

**Comment by elenavillamil** [comment]
@tophallen glad it helped :) So you can use port 80 on a pod, the message was saying that a service running locally on your machine **Service 'World Wide Web Publishing Service'** was using port 80. If port 80 is taken in your machine and your pod also uses port 80, then bridge cannot setup proper port forwarding. You have two options:

1. What you did, remove port 80 from the pod. 
2. Stop local service taking port 80 (in my opinion preferred option). You should be able to add port 80 back to templating-api if you stop World Wide Web publishing Service in your machine.

Regarding VS that seems something else not related ot bridge. VSCode and CLI use same backend code.

Hope this help! If nothing else I will close this issue.
