### ISSUE TITLE
Failed to pull image "bridgetokubernetes.azurecr.io/lpkremoteagent:1.0.0"

### ISSUE THREAD

**Issue by RonanFelipe** [Azure/Bridge-To-Kubernetes#161]
**Describe the bug**
Currently following the steps in the [documentation](https://learn.microsoft.com/en-us/visualstudio/bridge/bridge-to-kubernetes-vs-code) to start the debug in my kubernetes local application. 

**Mention the platform you are using**
VSCode version: 1.75.1
OS: Ubuntu 22.04.1

**To Reproduce**
1. Installed both extensions: Kubernetes and Bridge to Kubernetes VS Code Extension
2. As described in the docs...choose the service I want.
3. Enter a port for local tunnel debugging, tried 3001 and 80.
4. Choose debug launch.
5. Next choose if isolate my local version or not, tried both.
6. Select Debug icon and the newly added Kubernetes launch configuration.
7. Allowed the EndpointManager to run by typing my admin password.
8. Stay in the waiting process forever, then I started to investigate, could see that 2 new pods are being created, used the command `describe` to see what was happening. Error: ErrImagePull

VSCode terminal:
Retrieving the current context and credentials...
Validating the credentials to access the cluster...
Validating the requirements to replicate resources locally...
Redirecting traffic from the cluster to your machine...
Waiting for EndpointManager to come up ...
EndpointManager came up successfully.
Waiting for 'hidden-name-12345bdd88f-l6vx6' in namespace 'default' to reach running state...

One of the Pods that was created:
**Normal**   **Scheduled**  2m48s                default-scheduler  Successfully assigned default/hidden-name-84f85d47cf-m5988 to minikube
**Warning**  **Failed**     49s                  kubelet            Failed to pull image "bridgetokubernetes.azurecr.io/lpkremoteagent:1.0.0": rpc error: code = Unknown desc = context deadline exceeded
**Warning**  **Failed**     49s                  kubelet            Error: ErrImagePull
**Normal**   **BackOff**    48s                 kubelet           Back-off pulling image "bridgetokubernetes.azurecr.io/lpkremoteagent:1.0.0"
**Warning**  **Failed**     48s                  kubelet            Error: ImagePullBackOff
.....................................
I could find old issues in the previous repository that had this problem, like [this one](https://github.com/microsoft/mindaro/issues/45) and [this one](https://github.com/microsoft/mindaro/issues/106).

Any help is appreciated.

**Comment by elenavillamil** [comment]
Hi @RonanFelipe, thanks for all the details. Are you behind any firewall that would prevent success image pull from our public docker repository?

**Comment by RonanFelipe** [comment]
Hello @elenavillamil, thanks for answering. 
I'm not behind any firewall.
I got help from a teammate and solved it. I manually downloaded the image with `docker pull bridgetokubernetes.azurecr.io/lpkremoteagent:1.0.0` then tried the debug again and it all worked.

**Comment by elenavillamil** [comment]
Correct if user's minikube instance is having issues syncing our public images, then manual pull with docker is the only workaround.
