### ISSUE TITLE
Forward namespace without specifying service/pod/container

### ISSUE THREAD

**Issue by giulianob** [Azure/Bridge-To-Kubernetes#169]
I would like the ability to simply forward all of the services in my namespace to my local without redirecting traffic. This is useful when I am just running an app locally that needs access to all of the remote services.

**Comment by hsubramanianaks** [comment]
@giulianob Thanks for raising this issue. what do you mean **without specifying service/pod/container** ? when you configure bridge via vscode or visual studio it would ask you to pick as service, but your need is pick namespace and bridge has to forward all traffic for all the services in the namespace to your local ? is that correct ? I don't think Bridge supports this today, as a workaround you can have multiple instances of vscode running with each service running locally and debug via bridge to kubernetes (but this is inefficient). 

another option is vscode tasks.json you can define multiple services you want to debug in the same namespaces, and have them all checked out in local. (Unless it is mono repo it would be beneficial to have all services checked out once). Please let me know if this works or correct me If my understanding is wrong. Thank you again.

<img width="476" alt="image" src="https://user-images.githubusercontent.com/105889062/220419226-76afd00a-c018-4d3a-8ce7-af5127f587f7.png">

**Comment by giulianob** [comment]
I just want to make services that are running in my namespace to be available locally but I do not wish to replace any of the remote services. For example, I want to run some end to end tests from my local against services deployed in my namespace. It does not support this today but can this be kept as an enhancement?

**Comment by hsubramanianaks** [comment]
@giulianob Thanks for responding quickly. you are asking for remote debugging, there is work around for this , can you check if this works for you?  VSCode has a feature remote SSH where it allows to view code from remote machines, see if you can SSH into the machine and run the E2E test cases remotely might solve the issue But Bridge doesn't support this, and it is tool for local debugging. I feel like the ask is for different purpose and use case might not fit into bridge to Kubernetes. we will still consult with team and keep you updated.

**Comment by hsubramanianaks** [comment]
@giulianob can we close this issue ? Please let us know. Thanks.
