### ISSUE TITLE
Make kubectl commands timeout configurable

### ISSUE THREAD

**Issue by dgarberj** [Azure/Bridge-To-Kubernetes#179]
**Is your feature request related to a problem? Please describe.**
My issue is documented here: https://github.com/microsoft/mindaro/issues/267

**Mention what platform you want to support the new feature**
vscode

**Describe the solution you'd like**
I want my request to timeout at a time greater than the average expected time for my network. I want to be able to configure that somehow; maybe in VSCode settings.json

**Describe alternatives you've considered**
Increase the default timeout to 30s

**Additional context**

**Comment by matter-it-does** [comment]
same! 10s for kubectl env is too less

**Comment by dgarberj** [comment]
This is blocking my progress, unfortunately, in my work project. I noticed that the default satisfies my threshold needs, so to most quickly unblock myself and others, I propose a hotfix that will remove the override.

**Comment by Eneuman** [comment]
@elenavillamil I can make a PR for this if you want.

My implementation thoughts:

In KubernetesLocalProcessConfig.yaml we can add a new section:

timeouts:
 - name: kubectl
   value: 90

We can extend the list with more timeouts if needed.

If no values are set in KubernetesLocalProcessConfig.yaml it will use todays value as default.

What do you think?

**Comment by garyburgmann** [comment]
I agree, this is an annoying issue.

For what its worth @dgarberj, I work around this currently by invoking the specified task from `tasks.json` independently before invoking the debug script in `launch.json`. It simply detects the `preLaunchTask` is already running and starts straight up.

**Comment by hsubramanianaks** [comment]
@dgarberj Hi here is the VSIX to test - https://github.com/Azure/Bridge-To-Kubernetes/releases/tag/2.0.120230418
We released it as beta release, please set BRIDGE_ENVIRONMENT='dev' before installing and running this VSIX, thank you.

**Comment by dgarberj** [comment]
Hey, thank you for the workaround. Thankfully, this is no longer an issue for me in the latest release. Sent from my iPhoneOn Apr 17, 2023, at 1:03 AM, Gary Burgmann ***@***.***> wrote:﻿
I agree, this is an annoying issue.
For what its worth @dgarberj, I work around this currently by invoking the specified task from tasks.json independently before invoking the debug script in launch.json. It simply detects the preLaunchTask is already running and starts straight up.

**Comment by hsubramanianaks** [comment]
@dgarberj This is fixed with version 1.0.20230418.1, closing this issue. Please feel free to reopen if it happens still. Thank you.
