### ISSUE TITLE
PackageReference cleanup?

### ISSUE THREAD

**Issue by Eneuman** [Azure/Bridge-To-Kubernetes#185]
After the migration to .Net 6 some of the PackageReference are no longer needed since projects that target the Microsoft.NET.Sdk.Web SDK implicitly reference the Microsoft.AspNetCore.App framework.

Is there a need to target specific versions of the Microsoft packages or should these references be removed in favour of the shared framework versions?

I think using the shared framework is better from a security perspective since it will pick the version from the installed SDK on the build server.

I can make a PR for this if you want.

**Comment by elenavillamil** [comment]
@Eneuman , I agree shared framework is better. If it doesnt introduce any breaking changes it would be the way to go :) Thank you again for your help!
