### ISSUE TITLE
Could not connect to the remote agent because network traffic cannot be forwarded to port 80 as it is in use

### ISSUE THREAD

**Issue by jliglesias66** [Azure/Bridge-To-Kubernetes#189]
**Describe the bug**
I run B2k in VSCode and it works, but when I run it in Visual Studio 2022 v17.5.1 and launch a debug, I get a window with the error "Could not establish a connection to the cluster".

Looking in the traces I see the following:
C:\xxxxxx\Temp\Bridge To Kubernetes\bridge-library-2023-03-08-15-21-18-26280.txt
(sorry but the error message is in Spanish)

`2023-03-08T15:21:36.4509030Z | Library | TRACE | Event: ConnectManagementClient-StartServicePortForwardings <json>{"properties":{"result":"Failed"},"metrics":{"durationInMs":4.0}}</json>
2023-03-08T15:21:36.4512277Z | Library | ERROR | No se pudo conectar con el agente remoto.
2023-03-08T15:21:36.4701309Z | Library | ERROR | Logging handled exception: Microsoft.BridgeToKubernetes.Common.Exceptions.InvalidUsageException: {"Request":null,"Response":null,"RequestId":null,"ClientRequestId":null,"CorrelationRequestId":":b9c364f5b6f2:29cc17be0402","Format":"El proceso \"PID 4 No se puede obtener información de propiedad\" se enlaza al puerto \"80\" en todas las direcciones. Esto impedirá que \"Bridge To Kubernetes\" reenvíe el tráfico de red en este puerto. Detenga este proceso o servicio y vuelva a intentarlo.","Args":[],"Message":"El proceso \"PID 4 No se puede obtener información de propiedad\" se enlaza al puerto \"80\" en todas las direcciones. Esto impedirá que \"Bridge To Kubernetes\" reenvíe el tráfico de red en este puerto. Detenga este proceso o servicio y vuelva a intentarlo.","Data":{},"InnerException":null,"HelpLink":null,"Source":null,"HResult":-2146233088,"StackTrace":"   at Microsoft.BridgeToKubernetes.Library.Connect.LocalEnvironmentManager._StartServicePortForwardings(EndpointInfo endpointInfo)\r\n   at Microsoft.BridgeToKubernetes.Library.Connect.LocalEnvironmentManager.StartServicePortForwardings(Int32 remoteAgentLocalPort, IEnumerable`1 reachableEndpoints, CancellationToken cancellationToken)\r\n   at Microsoft.BridgeToKubernetes.Library.ManagementClients.ConnectManagementClient.<>c__DisplayClass25_0.<<StartServicePortForwardingsAsync>b__0>d.MoveNext()\r\n--- End of stack trace from previous location ---\r\n   at Microsoft.BridgeToKubernetes.Library.ManagementClients.ManagementClientExceptionStrategy.<>c__DisplayClass3_0.<<RunWithHandlingAsync>b__0>d.MoveNext()\r\n--- End of stack trace from previous location ---\r\n   at Microsoft.BridgeToKubernetes.Library.ManagementClients.ManagementClientExceptionStrategy.RunWithHandlingAsync[T](Func`1 func, FailureConfig failureConfig)"}
2023-03-08T15:21:36.4811332Z | Library | TRACE | Connecting to EndpointManager
2023-03-08T15:21:36.4818358Z | Library | TRACE | Received request segment: 'EndpointManager accepted connection<EOF>' of size 40`

**The question**
Is there any way to configure the launch to use another port than 80?

**Environment Details**
OS: Windows 11 x64 10.0.22621
VS Code: v4.8.09032 + B2k: v2.0.120230216 (**works**)
Microsoft Visual Studio Enterprise 2022 x64: v17.5.1 + B2k: v3.2.20230223.5 (**does't work**)

**Comment by jliglesias66** [comment]
I got it to work since it was the IIS that was using port 80 and stopping it was enough. 

Anyway I am curious to know if you can change the port to not use port 80 in Visual Studio.

**Comment by carlin-q-scott** [comment]
I have this issue and my kubernets cluster is using port 80. So it's not possible for me to turn it off.

**Comment by hsubramanianaks** [comment]
Hi thanks for raising this issue. @carlin-q-scott can you give a try using annotations below to ignore some ports and see if it works ?

```   
      metadata:
      name: my-service
      annotations:
       bridgetokubernetes/ignore-ports: "445,23"
```

**Comment by elenavillamil** [comment]
@jliglesias66 and @carlin-q-scott thank you for your issue. B2K does not hardcode any ports to use. B2K however sets port forwarding based on your cluster services. So if one of the services in your namespace is using port 80 then b2k will try to set up portforwarding on port 80 on your machine. So there are 3 options:
  - Stop the service using the port used by the kubernetes service (what you did)
  - Update the port your kubernetes service uses to a part that is not in use on your local machine
  - If you dont need forwarding set up with the service that uses port 80, then what @hsubramanianaks mentioned and ignore that port should work too.

Please also note that B2K currently does not work with kubernetes cluster for Docker Desktop. #132 gives more details on why docker desktop is not supported. Minikube, kind, or rancher-desktop are supported options for local cluster.

**Comment by jliglesias66** [comment]
Hello everyone again, and thank you for your answers.

If B2k does not modify any ports to use, how is it possible that the extension in VSCode works and in Visual Studio does not, being the same project/code against the same service being debugged?

**Comment by elenavillamil** [comment]
Is it possible that when you tried VsCode the service using port 80 wasnt running? Is it possible that Visual Studio starts SII automatically for you but VSCode doesnt? Sorry not sure what SII stands for.

**Comment by carlin-q-scott** [comment]
Thank you @elenavillamil and @hsubramanianaks . I understand that because Docker Desktop binds my LoadBalancer Service to port 80 and 443, common ports for this Service type, then B2K tries to bind them as well and throws an error. I will try to inform B2K to ignore this Service's ports using the suggested annotation and see if that fixes my issue.

**Comment by jliglesias66** [comment]
> Is it possible that when you tried VsCode the service using port 80 wasnt running? Is it possible that Visual Studio starts SII automatically for you but VSCode doesnt? Sorry not sure what SII stands for.

Thanks for your answer, I did not write SII, I wrote IIS (Internet Information Server). And no, neither Visual Studio nor VS Code, I have them configured to automatically start IIS.

**Comment by carlin-q-scott** [comment]
I'm not sure what those annotations I was given are supposed to do for me. B2K seems to always try to bind to my pod's port, even when I set the annotation on the pod to ignore the port. 

Can I disable this feature in Visual Studio somehow? My cluster is already handling my ports appropriately; I have HTTP/S access to the pod I want to debug at the exact same port B2K is trying to make a tunnel to/from. Why is it not using the nodePort? That would be safer than the internal cluster port.

**Comment by elenavillamil** [comment]
@carlin-q-scott, if you ignore the ports the nbridge wont set up forwarding for them, which I think is not what you want in this case (specially if the service being debug is the one using it). I think for this case since B2K doesnt support kubernetes cluster for docker desktop, your best option is try to use another local cluster solution like minikube. Apologies for that inconvinience.

@jliglesias66 thank you for clarifying (sorry I got my letters confused :) ). From [this article](https://learn.microsoft.com/en-us/previous-versions/aspnet/58wxa9w5(v=vs.120)) it seems Visual Studio starts IIS automatically for you and that is why you ran into the issue with VS and not VSCode (I think for VSCode you have to have to have a specific extension installed [more details I found](https://stackoverflow.com/questions/45736495/how-can-vs-code-be-configured-to-run-and-debug-with-iis-express-and-asp-net-core)). If you still want to use VS instead of VSCode and you dont need IIS running, then that seems the way to go :) If you need IIS running and you still want to keep using Visual Studio you could try to change your deployment spec to assign a different port for your service? Hope this helps.

**Comment by jliglesias66** [comment]
@elenavillamil, I think I didn't explain myself well, IIS was not started by the development environment, I had it running because on my computer it is needed for other third party software solutions. So, what I wanted to know was how B2k can be configured to not use port 80 in Visual Studio, since in VS Code it was not necessary. Sorry for misleading.

**Comment by elenavillamil** [comment]
@jliglesias66 sorry for any confusion. I am trying to say that there is nothing in B2K that will hardcode using port 80 on VisualStudio. Users can use b2k to debug services that use port 80 on VS same as in VSCode. I was trying to say that maybe below is what is happening on your case? So even if you stop IIS running on your machine, when you started up the application in Visual Studio it started IIS automatically for you? Could you use netstat to see which process ID is using the port 80 when you run into this conflict port error in VS?
<img width="841" alt="Screenshot 2023-03-16 at 1 29 14 PM" src="https://user-images.githubusercontent.com/4663400/225746700-a686f710-27b3-4788-ba5a-ad2c24108447.png">

**Comment by sabbour** [comment]
Related:
https://github.com/Azure/Bridge-To-Kubernetes/issues/132
https://www.docker.com/blog/dockershim-not-needed-docker-desktop-with-kubernetes-1-24/#:~:text=Docker%20Desktop%20automatically%20binds%20network%20ports%20on%20the,remembering%20internal%20IP%20addresses%20or%20reconfiguring%20their%20DNS.

**Comment by hsubramanianaks** [comment]
Please feel free to reopen if this still happens or needs assistance. Thank you.
