### ISSUE TITLE
How to completely delete the restore pod?

### ISSUE THREAD

**Issue by RonanFelipe** [Azure/Bridge-To-Kubernetes#215]
**Describe the bug**
Application is running inside the debug, debug works fine. Everything is working. Then let's say Ubuntu crashed while VSCode was opened and Bridge was connected to debug. I restart my computer, restart all my services/pods, try to run Debug again and get the error `"Restoration pod is still present for the specified service 'my-service-name'. This means service has a bridge session still running. Please ensure bridge is fully disconnected and try again once the service is restored."`   

Ok so since it was a crash I don't have that button `'Disconnect current session'`, I check the list of pods and services `kubectl get services,deployments,pods` and I see all my services/pods are there and one particular one the `my-service-name-restore-1234-5678` with Status running. I tried to delete it `kubectl delete pods my-service-name-restore-1234-5678`, it works for 1 second then it restart with a new name, then I try to force it `kubectl delete pods my-service-name-restore-4567-8910 --force --grace-period=0 --namespace=default` and got same result, it delete and in 1 second it restart it again. So searching online I got to the point that I had to stop all my services/deployments/pods to make it work, also disabled the extension, closed VSCode, got to the point that everything was deleted and one single pod was still there `my-service-name-restore-9876-5432` then I finally could remove it completely and start all my services/deployments/pods again, opened VSCode, enable Bridge-To-Kubernets, restarted VSCode, and finally connected debug again, everything working fine.

So I'm going too naive here because of lack of experience on this topic, but is there a better method to deal with this problem when a crash on the operation system happen? 

**Mention the platform you are using**
Ubuntu 22.04
VSCode 1.76.1
Bridge-To-Kubernetes v2.0.120230310

**Comment by elenavillamil** [comment]
Hi @RonanFelipe, good question. In this scenario I would do the follow:
- kubectl describe <pod you were debugging> and ensure image running is your service image (if you see and image that looks like "Image:          mindarodev.azurecr.io/lpkremoteagent:1.1.0" that means bridge didnt restore). I dont think this will be the case, but if it is let me know and I will share different steps.
- run: kubectl get all. Search for restore job, it will look like below
```
NAME                                COMPLETIONS   DURATION   AGE
job.batch/stats-api-restore-eaf0d   0/1           111s       111s
```
- run: kubectl delete job.batch/stats-api-restore-eaf0d

**Comment by Eneuman** [comment]
@RonanFelipe
After deleting the job, you can rollback the deployment of the DevHostAgent by first list the deployments like this:


kubectl rollout history deploy mydeployment

And the rollback to a earlier version like this:


kubectl rollout undo deploy mydeployment --to-revision=1



Mvh

Per Bornsjö



___________________________________
[links_loggo]

Per Bornsjö

LINKS GOT AB
BOX 13103<x-apple-data-detectors://0/1>
S-402 52 GÖTEBORG<x-apple-data-detectors://0/1>
MOB: 070-5888337<tel:070-5888337>

***@***.******@***.***> • www.links.se<http://www.links.se/>

This e-mail is confidential and may contain

________________________________
Från: elenavillamil ***@***.***>
Skickat: Wednesday, March 22, 2023 9:48:57 PM
Till: Azure/Bridge-To-Kubernetes ***@***.***>
Kopia: Subscribed ***@***.***>
Ämne: Re: [Azure/Bridge-To-Kubernetes] How to completely delete the restore pod? (Issue #215)


Hi @RonanFelipe<https://github.com/RonanFelipe>, good question. In this scenario I would do the follow:

  *   kubectl describe and ensure image running is your service image (if you see and image that looks like "Image: mindarodev.azurecr.io/lpkremoteagent:1.1.0" that means bridge didnt restore). I dont think this will be the case, but if it is let me know and I will share different steps.
  *   run: kubectl get all. Search for restore job, it will look like below

NAME                                COMPLETIONS   DURATION   AGE
job.batch/stats-api-restore-eaf0d   0/1           111s       111s


  *   run: kubectl delete job.batch/stats-api-restore-eaf0d
