### ISSUE TITLE
Upgrade to .Net 7

### ISSUE THREAD

**Issue by Eneuman** [Azure/Bridge-To-Kubernetes#228]
I have been running .Net 7 in my local builds of B2K for about 4 weeks now and everything works great.
.Net 7 have new AOT compilation features and other performance improvements that I think would be a great addition to everyone using this product.

If you want I can make a PR for upgrading it to .Net 7?

**Comment by hsubramanianaks** [comment]
@Eneuman Thanks for the recommendations. we can wait until all the open PRs are reviewed tested, merged and then move to this item? 
I appreciate your participation and patience. :)

**Comment by Eneuman** [comment]
@hsubramanianaks Sure, sounds good!

**Comment by Tatsinnit** [comment]
Hiya @Eneuman and @hsubramanianaks - fyi - both your votes will be amazing here: https://github.com/Azure/Bridge-To-Kubernetes/discussions/266 Thanks. ☕️🙏 Sorry for hijacking this PR I will look soon, but thought will get your attention to this poll which will decide our loss communication channel idea. Thanks

**Comment by hsubramanianaks** [comment]
Closing this since this rolled out to production. Thanks @Eneuman for your great contributions and discussions. :)
