### ISSUE TITLE
DevAgent ReversePortForwardManger Remote Connection Closed error

### ISSUE THREAD

**Issue by SteveCurran** [Azure/Bridge-To-Kubernetes#23]
I am running latest extension from vscode with local k3s using ubuntu 20.04. Everything works when debugging a non-edge (front end) container. However, when trying to debug a edge (front end) container it never hits the break point. Looking at the devagent logs I see the websocket is created, then immediately, the "remote connection closed". The restoration agent container continues to fail after 12 unsuccessful ping attempts (connection refused) to the devagent container.  After stopping the debug session the restoration job never executes because of the connection problem. The only difference between the edge container and non-edge container is the edge container is using aspnetcore kestrel. I thought maybe this was related to running behind a reverse proxy so I set the allowedhosts setting to localhost, but no luck.
[bridge-library.txt](https://github.com/Azure/Bridge-To-Kubernetes/files/9387675/bridge-library.txt)
[bridge-restoration-job.log](https://github.com/Azure/Bridge-To-Kubernetes/files/9387676/bridge-restoration-job.log)

**Comment by SteveCurran** [comment]
It appears that btk has trouble with containers running aspnet core kestrel and with the URLS host configuration environment variable set. Setting this appears to lock down the container from receiving any connection from a port other than what is set in the URLS environment variable. Switching to ASPNETCORE_URLS fixes the issue. Having both present still breaks btk.

**Comment by qpetraroia** [comment]
Hi @SteveCurran, 

Are you running on an AKS cluster? Arc cluster?

**Comment by SteveCurran** [comment]
@qpetraroia I am running a local k3s cluster.

**Comment by hsubramanianaks** [comment]
@SteveCurran when you mean URLs host configuration environment variable set , is it appsettings urls ?

**Comment by elenavillamil** [comment]
@SteveCurran , correct since having those will lock container ports other than specified in the URL. This means b2k controller running on your local machine wont be able to communicate with devhostagent (b2k client on the cluster) because this communication happens on port 50052.

Glad there is a workaround :)
