### ISSUE TITLE
Visual Studio 2022 - Using bridge not able to connect to AKS cluster

### ISSUE THREAD

**Issue by arunkumarnr** [Azure/Bridge-To-Kubernetes#236]
**Describe the bug**
Trying to setup bridge for aks as per https://learn.microsoft.com/en-us/visualstudio/bridge/bridge-to-kubernetes-vs using Visual Studio 2022 with latest version (17.5.X) but it says 

![image](https://user-images.githubusercontent.com/34078364/230143048-c8fe83a4-44c5-473b-9a26-03642300ed3c.png)

I'm using Visual Studio 2022 17.5.3

**To Reproduce**
1. Followed https://learn.microsoft.com/en-us/visualstudio/bridge/bridge-to-kubernetes-vs but not able to connect.

**Expected behavior**
Should able to connect and debug microservice from Visual Studio 2022

**Screenshots**
![image](https://user-images.githubusercontent.com/34078364/230143048-c8fe83a4-44c5-473b-9a26-03642300ed3c.png)

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro
 - Version : 22H2 (22621.1413)

**Comment by sabbour** [comment]
Hi @arunkumarnr , to help us triage the issue, can you please share the log file at `C:\Users\<userid>\AppData\Local\Temp\Bridge To Kubernetes`?

**Comment by arunkumarnr** [comment]
Attaching the log files 

[bridge-endpointmanager-2023-04-05-20-41-10-44352.zip](https://github.com/Azure/Bridge-To-Kubernetes/files/11162972/bridge-endpointmanager-2023-04-05-20-41-10-44352.zip)

Note: Sample app works (able to debug) with the same AKS environment from VS Code but not from VS2022

**Comment by hsubramanianaks** [comment]
@arunkumarnr can you please try with latest version of b2k and see if issue still persists? if you face the issue, please share all the logs, thanks.

**Comment by hsubramanianaks** [comment]
@arunkumarnr is there any update on this ? Please let us know, thanks.

**Comment by hsubramanianaks** [comment]
@arunkumarnr Please feel free to reopen this issue if it happens again. Thank you.
