### ISSUE TITLE
Failed to Launch EndpointManager Ubuntu 22.04

### ISSUE THREAD

**Issue by SteveCurran** [Azure/Bridge-To-Kubernetes#238]
**Describe the bug**
Try to debug on ubuntu 22.04 from VSCode, launching endpoint manager, prompts for credentials, then fails.

**Mention the platform you are using**
VSCode, Ubuntu 22.04, K3s local

Looks like possible permission issue. No problems on Ubuntu 20.04
[bridge-mindarocli-2023-04-11-16-35-06-310311.txt](https://github.com/Azure/Bridge-To-Kubernetes/files/11202963/bridge-mindarocli-2023-04-11-16-35-06-310311.txt)

**Comment by hsubramanianaks** [comment]
@SteveCurran Thanks for raising this issue. do you find ```bridge-endpointmanager``` log files ? if so can you share them and library logs as well please.

**Comment by hsubramanianaks** [comment]
@SteveCurran Please feel free to open this issue again if it happens. Closing this for now, thanks.
