### ISSUE TITLE
Update Kubernetes Client nuget packages

### ISSUE THREAD

**Issue by Eneuman** [Azure/Bridge-To-Kubernetes#240]
Today Bridge To Kubernetes uses version 8.0 of the official Nuget packages for Kubernetes.
This version is compatible with Kubernetes API version 1.24, 1.25, 1.26

Now that version 1.27 is released we should consider upgrading to version 9.1 that "should" be compatible with 1.27.
Upgrading "might" remove support for 1.24 (EOL 28 Jul 2023).

References:
https://github.com/kubernetes-client/csharp
https://kubernetes.io/releases/version-skew-policy/
https://kubernetes.io/releases/

**Comment by hsubramanianaks** [comment]
@Eneuman I updated k8s client for csharp to latest in this [PR](https://github.com/Azure/Bridge-To-Kubernetes/pull/258), just letting you know. Thank you.

**Comment by Eneuman** [comment]
@hsubramanianaks I can see that your PR has been merged so I'm closing this issue:)
