### ISSUE TITLE
Cannot update the extension: From 3.2.20230314.5 to 3.2.20230331.1

### ISSUE THREAD

**Issue by jaliyaudagedara** [Azure/Bridge-To-Kubernetes#259]
I am not able to update the Visual Studio 2022 extension from `3.2.20230314.5` to `3.2.20230331.1`.
![image](https://user-images.githubusercontent.com/5653381/234739087-e74bed39-2e30-4212-8de1-e96df3ed4f66.png)

After downloading, when trying to install, getting this error.
![image](https://user-images.githubusercontent.com/5653381/234740621-7cac1072-3e7e-4998-b126-e41fc0dfd8c7.png)

* Platform/Version
```
Microsoft Visual Studio Enterprise 2022 (64-bit) - Preview
Version 17.6.0 Preview 5.0
```

**Comment by hsubramanianaks** [comment]
@jaliyaudagedara we are aware of this issue, working with VS marketplace team on this issue. Thank you for raising this issue. We will keep you posted on this.

**Comment by hsubramanianaks** [comment]
@jaliyaudagedara we have release a new version last night, can you please verify and let us know if this is working ? Thanks. 

version: 3.2.20230505.1

**Comment by jaliyaudagedara** [comment]
@hsubramanianaks, 

Vertified, all good. 
![image](https://github.com/Azure/Bridge-To-Kubernetes/assets/5653381/efabd423-75c2-489c-961c-a88232833c05)

Thanks a lot!
