### ISSUE TITLE
Neither any api endpoint is accessible nor any breakpoints hits for service startup code when debugging through B2K

### ISSUE THREAD

**Issue by ajmal-yazdani** [Azure/Bridge-To-Kubernetes#285]
**Describe the bug**
Neither any api endpoint is accessible nor any breakpoints hits for service startup code when debugging through B2K

**Mention the platform you are using**
Visual Studio 2022

**To Reproduce**
1. I have web api running in AKS cluster and Nginx Load Balancer is configured with custom DNS and API endpoint is accessible:
     
     https://dev-aks.company.com/SkeletonService/Test

Only one replica is running:

![image](https://github.com/Azure/Bridge-To-Kubernetes/assets/1866370/f431dc8a-ae4e-4c17-bd43-9bb83bda124b)

2. Now when I started debugging session through B2K using Visual Studio 2022:

![image](https://github.com/Azure/Bridge-To-Kubernetes/assets/1866370/4540e2ec-6533-4d8b-aa07-5c3743f14ff1)

Then I noticed 3 things:

A. My existing running POD replicaset gets re-started plus one more POD added which controlled by Job (not sure why)

![image](https://github.com/Azure/Bridge-To-Kubernetes/assets/1866370/e305c220-f737-434d-a5aa-009e19342890)

B. I noticed below debug console out and non of the service startup breakpoint hits:

![image](https://github.com/Azure/Bridge-To-Kubernetes/assets/1866370/d1df6a6d-73fe-4b6b-b7f5-c1464c85e7a6)

C.  API endpoint NO longer accessible:
      https://dev-aks.company.com/SkeletonService/Test

Please suggest what I am missing here.

**Comment by hsubramanianaks** [comment]
@ajmal-yazdani Thanks for raising this issue. Can you please share the logs from ```C:\Users\yourid\AppData\Local\Temp\Bridge To Kubernetes``` I can look further. The pod with ```-restore``` is created by b2k which is fine because once b2k session is terminated or disconnected, that pod is responsible to put back to original state. Yes of course the pod you are debugging will be replaced with another pod by b2k to intercept traffic from/to cluster. I need the log files to see if there are any errors, may be the port you are using is used by some system services in windows would cause break point not hit.

**Comment by ajmal-yazdani** [comment]
@hsubramanianaks , Thank you for your response. Please find logs at below location,

https://github.com/ajmal-yazdani/application/blob/master/b2k_logs.zip

**Comment by hsubramanianaks** [comment]
@ajmal-yazdani Thanks for the logs. I don't see any issue for this. Are the ports correct for the services that are running in k8s cluster ? ex: skeleton-service is running in port 5588 ? because in logs I see reverse port forward info is missing which is for break points to hit for traffic from cluster to your local machine. 

{
    "dnsName": "skeleton-service",
    "localIP": "127.1.1.1",
    "ports": [
        {
            "localPort": 5588,
            "remotePort": 5588,
            "protocol": "tcp",
            "name": null
        }
    ],
    "isExternalEndpoint": false,
    "isInWorkloadNamespace": true
},
{
    "dnsName": "redis-cache",
    "localIP": "127.1.1.2",
    "ports": [
        {
            "localPort": 6379,
            "remotePort": 6379,
            "protocol": "tcp",
            "name": "tcp-redis"
        },
        {
            "localPort": 26379,
            "remotePort": 26379,
            "protocol": "tcp",
            "name": "tcp-sentinel"
        }
    ],
    "isExternalEndpoint": false,
    "isInWorkloadNamespace": true
},
{
    "dnsName": "redis-cache-node-0.redis-cache-headless",
    "localIP": "127.1.1.3",
    "ports": [
        {
            "localPort": 6379,
            "remotePort": 6379,
            "protocol": "tcp-redis",
            "name": null
        },
        {
            "localPort": 26379,
            "remotePort": 26379,
            "protocol": "tcp-sentinel",
            "name": null
        }
    ],
    "isExternalEndpoint": false,
    "isInWorkloadNamespace": true
},
{
    "dnsName": "redis-cache-node-1.redis-cache-headless",
    "localIP": "127.1.1.4",
    "ports": [
        {
            "localPort": 6379,
            "remotePort": 6379,
            "protocol": "tcp-redis",
            "name": null
        },
        {
            "localPort": 26379,
            "remotePort": 26379,
            "protocol": "tcp-sentinel",
            "name": null
        }
    ],
    "isExternalEndpoint": false,
    "isInWorkloadNamespace": true
},
{
    "dnsName": "redis-cache-node-2.redis-cache-headless",
    "localIP": "127.1.1.5",
    "ports": [
        {
            "localPort": 6379,
            "remotePort": 6379,
            "protocol": "tcp-redis",
            "name": null
        },
        {
            "localPort": 26379,
            "remotePort": 26379,
            "protocol": "tcp-sentinel",
            "name": null
        }
    ],
    "isExternalEndpoint": false,
    "isInWorkloadNamespace": true
}

**Comment by ajmal-yazdani** [comment]
Hi. Yes ports are correct.

**Comment by MichaelPetrinolis** [comment]
I have the same issue. The breakpoints hit while loading the POD or when a message handler is triggered. When accessing the service through the NGINX load balancer, error 502. The POD uses a Workload Identity while the NGINC controller a managed identity. The cluster is Azure RBAC enabled allowing local admins.

**Comment by hsubramanianaks** [comment]
@MichaelPetrinolis can you share the logs from ```C:\Users\<yourid>\AppData\Local\Temp\Bridge To Kubernetes``` please ? I can check further.

**Comment by MichaelPetrinolis** [comment]
Hi @hsubramanianaks, thank you for your time.

here are the logs you requested [b2k_logs](https://lighthouseazure-my.sharepoint.com/:u:/g/personal/mpetrinolis_corp_lighthouse_gr/EUphzq5nXwRDlxjBtnms2twBeE9XI9x-ZF0yR6RQTe1geQ?e=R5swEv)

FYI: I updated VS2022 from 17.5.5 to 17.6.4 (had the latest b2k extension installed) and rebooted my machine before I collect the logs.

**Comment by ajmal-yazdani** [comment]
I have 2 more observation apart from same observation from @MichaelPetrinolis :

1. While adding breakpoint, it's warns that symbol are not loaded.
![image](https://github.com/Azure/Bridge-To-Kubernetes/assets/1866370/bf867de4-db66-4e04-9402-ac31babeee3c)

3. Docker desktop stopped and trying to re-start. Until and unless I rebooted my machine, docker not working.
![image](https://github.com/Azure/Bridge-To-Kubernetes/assets/1866370/ba87a7ae-5d6e-4579-a6aa-d29ed0aada6d)

**Comment by MichaelPetrinolis** [comment]
UPDATE:
If I connect to a pod of a different service and install curl, when hitting the service under debug I get empty response. As soon as I stop the debugger, the curl command works as expected.

**Comment by MichaelPetrinolis** [comment]
SOLVED:
I figured out what was causing this behavior in my case. I use SSL Offload on NGINX so the internal service uses HTTP and not HTTPS. But in launch configuration - "Project" command -, I removed the HTTP endpoint from "applicationUrl" 
That caused the local service on my machine to be bound on HTTPS only and did not reply to HTTP calls.

**Comment by hsubramanianaks** [comment]
@ajmal-yazdani @MichaelPetrinolis Please reopen this issue or create new one if this is still happening. Thank you.
