### ISSUE TITLE
Jaeger sidecar makes b2k fail

### ISSUE THREAD

**Issue by BartNetJS** [Azure/Bridge-To-Kubernetes#292]
When I annotate a deployment with sidecar.jaegertracing.io/inject to add a jaeger sidecar to the pod, b2k stops working with the message 
`Error: Failed to validate the requirements to replicate resources locally: Failed to identify the container to use in pod '.....-5786c96cf8-csq96'.
`
Jaeger agent is working fine and b2k debugging session also without the jaeger agent

**Comment by hsubramanianaks** [comment]
@BartNetJS Thanks for raising this issue. Can you send all the logs from location ```$HOME/tmp/Bridge To Kubernetes``` ? Jaeger is not supported side car proxy, I think making a simple code change [here](https://github.com/Azure/Bridge-To-Kubernetes/blob/main/src/library/Extensions/V1ContainerExtensions.cs#L12) might fix your issue. I will look further into once you send me the logs.

**Comment by BartNetJS** [comment]
@hsubramanianaks hereby the log.
Are you gone make that change? Or will I contribute?
[vscode-logs.zip](https://github.com/Azure/Bridge-To-Kubernetes/files/12024961/vscode-logs.zip)

**Comment by hsubramanianaks** [comment]
@BartNetJS Thanks for the logs, looking at the logs yep as I suspected it needs code changes to support Jeager. We welcome contributions, if you have the time to make the changes it will be better. Thank you. Please let me know.

**Comment by hsubramanianaks** [comment]
This is released to production, feel free to test and close this issue. Thank you for your contribution. @BartNetJS
