### ISSUE TITLE
Unable to connect to endpoint manager in July release

### ISSUE THREAD

**Issue by SteveCurran** [Azure/Bridge-To-Kubernetes#297]
**Describe the bug**
Starting bridge to debug and prompt for credentials to edit host file produces the following error:

Bridge to Kubernetes initialization (VS Code v1.80.1 - Extension v2.0.120230716)
Logs: /home/steve/.config/Code/logs/20230719T111012/window1/exthost/mindaro.mindaro/mindaro-vscode-2023-07-19T16-10-16.415Z.txt
Waiting for EndpointManager to come up ...
An unexpected error occurred: 'Failed to launch EndpointManager.'
To see our active issues or file a bug report, please visit https://aka.ms/bridge-to-k8s-report.
For diagnostic information, see logs at '/tmp/Bridge To Kubernetes'.
Failed to establish a connection. Error: An unexpected error occurred: 'Failed to launch EndpointManager.'
To see our active issues or file a bug report, please visit https://aka.ms/bridge-to-k8s-report.
For diagnostic information, see logs at '/tmp/Bridge To Kubernetes'.

Using Ubuntu 20.04 and local K3s

Just started happening, I have tried using the previous version same thing.
[bridge-mindarocli-2023-07-19-17-10-32-58500.txt](https://github.com/Azure/Bridge-To-Kubernetes/files/12098444/bridge-mindarocli-2023-07-19-17-10-32-58500.txt)

**Comment by hsubramanianaks** [comment]
@SteveCurran Can you share all the logs files from ```'/tmp/Bridge To Kubernetes'.``` ? Thanks for letting us know, we will look further into it.

**Comment by SteveCurran** [comment]
@hsubramanianaks here is the complete set of logs, fyi, this ubuntu is running dotnet 6.0.4
[bridge-library-2023-07-19-19-38-05-110905.txt](https://github.com/Azure/Bridge-To-Kubernetes/files/12099619/bridge-library-2023-07-19-19-38-05-110905.txt)
[bridge-library-2023-07-19-19-40-40-112627.txt](https://github.com/Azure/Bridge-To-Kubernetes/files/12099620/bridge-library-2023-07-19-19-40-40-112627.txt)
[bridge-library-2023-07-19-19-40-52-113012.txt](https://github.com/Azure/Bridge-To-Kubernetes/files/12099621/bridge-library-2023-07-19-19-40-52-113012.txt)
[bridge-library-2023-07-19-19-40-53-113057.txt](https://github.com/Azure/Bridge-To-Kubernetes/files/12099622/bridge-library-2023-07-19-19-40-53-113057.txt)
[bridge-library-2023-07-19-19-40-54-113077.txt](https://github.com/Azure/Bridge-To-Kubernetes/files/12099623/bridge-library-2023-07-19-19-40-54-113077.txt)
[bridge-library-2023-07-19-19-40-58-113135.txt](https://github.com/Azure/Bridge-To-Kubernetes/files/12099624/bridge-library-2023-07-19-19-40-58-113135.txt)
[bridge-mindarocli-2023-07-19-19-38-04-110668.txt](https://github.com/Azure/Bridge-To-Kubernetes/files/12099625/bridge-mindarocli-2023-07-19-19-38-04-110668.txt)
[bridge-mindarocli-2023-07-19-19-38-05-110905.txt](https://github.com/Azure/Bridge-To-Kubernetes/files/12099626/bridge-mindarocli-2023-07-19-19-38-05-110905.txt)
[bridge-mindarocli-2023-07-19-19-40-38-112416.txt](https://github.com/Azure/Bridge-To-Kubernetes/files/12099627/bridge-mindarocli-2023-07-19-19-40-38-112416.txt)
[bridge-mindarocli-2023-07-19-19-40-39-112627.txt](https://github.com/Azure/Bridge-To-Kubernetes/files/12099628/bridge-mindarocli-2023-07-19-19-40-39-112627.txt)
[bridge-mindarocli-2023-07-19-19-40-52-113012.txt](https://github.com/Azure/Bridge-To-Kubernetes/files/12099629/bridge-mindarocli-2023-07-19-19-40-52-113012.txt)
[bridge-mindarocli-2023-07-19-19-40-53-113057.txt](https://github.com/Azure/Bridge-To-Kubernetes/files/12099630/bridge-mindarocli-2023-07-19-19-40-53-113057.txt)
[bridge-mindarocli-2023-07-19-19-40-54-113077.txt](https://github.com/Azure/Bridge-To-Kubernetes/files/12099631/bridge-mindarocli-2023-07-19-19-40-54-113077.txt)
[bridge-mindarocli-2023-07-19-19-40-58-113135.txt](https://github.com/Azure/Bridge-To-Kubernetes/files/12099632/bridge-mindarocli-2023-07-19-19-40-58-113135.txt)

**Comment by hsubramanianaks** [comment]
@SteveCurran I am seeing ```2023-07-19T19:41:07.3324854Z | Library | TRACE | EndpointManager is not running: 'Cannot assign requested address'``` this error happens if your OS network setting are not configured properly or sometimes rebooting your system might help. Are you using native ubuntu or SSHing into remote machine? I will keep researching about this error and planning to add a live test for ubuntu with endpoint manager as improvement. 

Also did you find any logs with bridge-endpointmanager-*.txt ? because in your case endpoint manager didn't start successfully.  Please confirm on this. 

Thanks for providing the logs.

**Comment by SteveCurran** [comment]
@hsubramanianaks No EndpointManager folder in the $HOME/.bridge folder. Installed dotnet sdk 7.0 "sudo apt-get install -y dotnet-sdk-7.0" and everything works. So b2k requires 7.0 to be installed? This is pre-built ubuntu VM using the quick create option from Hyper-V manager. So I guess I need to add 7.0 sdk.

**Comment by hsubramanianaks** [comment]
@SteveCurran thanks for confirming, yes July release upgraded them to dotnet 7. I wonder why it would require updating to dotnet 7.0 in your local where bridge downloads them for the user in the following location and set's the DOTNET_ROOT which will be used while launching endpointmanager file. Can you please check what's the dotnet version in the location below where bridge vscode extension downloads dotnet libraries. My guess is either it is not downloading dotnet 7.0 libraries or while launching it is not using this location instead looking into the local dotnet install location ex:/usr/share/dotnet etc.. Trying to find if there is a bug or needs process improvement. Please let me know, thank you. 

```2023-07-19T19:41:00.3579268Z | Library | TRACE | Setting the 'DOTNET_ROOT' environment variable with '/home/steve/.config/Code/User/globalStorage/mindaro.mindaro/file-downloader-downloads/dotnet' while launching 'EndpointManager'.```

**Comment by SteveCurran** [comment]
@hsubramanianaks 7.0.7 binaries appear in that location and are being downloaded. I do know that before I installed dotnet sdk  7.0 I ran "dotnet --info" and it listed only the 6.0 sdk. It also states no environment variables are set. The only thing then is setting DOTNET_ROOT is not sufficient for the code to execute. It is only affects the current terminal session.

**Comment by davidfu13** [comment]
This issues also occurs to my Ubuntu 22.04. 
The trace also contains the following logs
```
bridge-library-2023-10-24-08-13-26-8788.txt:134:2023-10-24T08:14:00.7823912Z | Library | TRACE | EndpointManager is not running: 'Cannot assign requested address'
bridge-library-2023-10-24-08-13-26-8788.txt:135:2023-10-24T08:14:01.2809428Z | Library | TRACE | Connecting to EndpointManager
```
I tried reboot my OS but it still don't work

**Comment by davidfu13** [comment]
> @davidfu13 did you try with latest release ? Can you try & let me know the error. Also what's the dotnet version in your Ubuntu 22? Thank you.

The version of Bride to Kubernetes I use is `v2.0.120231004` which I suppose is the latest release?
Below are some relevant infromation:
vscode version: `1.83.1`
dotnet version in my Ubuntu 22: `6.0.123`
The version of dotnet in the DOTNET_ROOT directory:
```
~/.co/Code/User/globalStorage/mindaro.mindaro/file-downloader-downloads/dotnet ❯ ./dotnet --info                                                                                                    х HUP 11:09:06

Host:
  Version:      7.0.7
  Architecture: x64
  Commit:       5b20af47d9
```

complete set of logs:
[bridge-library-2023-10-25-03-00-43-64130.txt](https://github.com/Azure/Bridge-To-Kubernetes/files/13160917/bridge-library-2023-10-25-03-00-43-64130.txt)
[bridge-library-2023-10-25-03-01-08-64191.txt](https://github.com/Azure/Bridge-To-Kubernetes/files/13160918/bridge-library-2023-10-25-03-01-08-64191.txt)
[bridge-library-2023-10-25-03-01-23-64256.txt](https://github.com/Azure/Bridge-To-Kubernetes/files/13160919/bridge-library-2023-10-25-03-01-23-64256.txt)
[bridge-library-2023-10-25-03-01-26-64283.txt](https://github.com/Azure/Bridge-To-Kubernetes/files/13160921/bridge-library-2023-10-25-03-01-26-64283.txt)
[bridge-library-2023-10-25-03-01-30-64304.txt](https://github.com/Azure/Bridge-To-Kubernetes/files/13160922/bridge-library-2023-10-25-03-01-30-64304.txt)
[bridge-library-2023-10-25-03-01-36-64332.txt](https://github.com/Azure/Bridge-To-Kubernetes/files/13160923/bridge-library-2023-10-25-03-01-36-64332.txt)
[bridge-mindarocli-2023-10-25-03-00-42-64130.txt](https://github.com/Azure/Bridge-To-Kubernetes/files/13160924/bridge-mindarocli-2023-10-25-03-00-42-64130.txt)
[bridge-mindarocli-2023-10-25-03-01-08-64191.txt](https://github.com/Azure/Bridge-To-Kubernetes/files/13160925/bridge-mindarocli-2023-10-25-03-01-08-64191.txt)
[bridge-mindarocli-2023-10-25-03-01-22-64256.txt](https://github.com/Azure/Bridge-To-Kubernetes/files/13160926/bridge-mindarocli-2023-10-25-03-01-22-64256.txt)
[bridge-mindarocli-2023-10-25-03-01-25-64283.txt](https://github.com/Azure/Bridge-To-Kubernetes/files/13160927/bridge-mindarocli-2023-10-25-03-01-25-64283.txt)
[bridge-mindarocli-2023-10-25-03-01-29-64304.txt](https://github.com/Azure/Bridge-To-Kubernetes/files/13160928/bridge-mindarocli-2023-10-25-03-01-29-64304.txt)
[bridge-mindarocli-2023-10-25-03-01-36-64332.txt](https://github.com/Azure/Bridge-To-Kubernetes/files/13160929/bridge-mindarocli-2023-10-25-03-01-36-64332.txt)

**Comment by davefu113** [comment]
@hsubramanianaks it works now after I upgrade my Ubuntu 22.04 local dotnet from `6.0.123` to `7.0.112`

**Comment by davidfu13** [comment]
@hsubramanianaks it works now after I upgrade my Ubuntu 22.04 local dotnet from 6.0.123 to 7.0.112

**Comment by hsubramanianaks** [comment]
@davidfu13 @SteveCurran Thanks for all details, I am able to replicate this. Basically, if your Linux doesn't have dotnet installed or has an outdated dotnet that b2k is expecting then it would give this error. Because there is code to set the process to start ([here](https://github.com/Azure/Bridge-To-Kubernetes/blob/main/src/library/EndpointManagement/EndpointManagerLauncherBase.cs#L66)) endpoint manager with environment variable DOTNET_ROOT and path to set, but it is not recognizing that variable and fails. I will research more about this and will have a fix if I find something. Thanks for your patience. Only workaround is to install dotnet 7 in your Linux.

**Comment by hsubramanianaks** [comment]
@SteveCurran Please reopen this issue if it happens again, thank you.

**Comment by simonpinn** [comment]
Can also confirm (running on Ubuntu 22.04) @hsubramanianaks that I had the exact same problem, had dotnet SDK 5,6 and 8 but not 7, scratched my head for a while and found this thread, installed SDK 7 and all worked! Thanks @SteveCurran
