### ISSUE TITLE
Bridge to Kubernetes VS 2022 extension - timeout exception

### ISSUE THREAD

**Issue by stevendarby** [Azure/Bridge-To-Kubernetes#301]
**Describe the bug**
I can no longer bridge using the Bridge to Kubernetes VS 2022 extension. 

**Mention the platform you are using**
Windows 10
VS 2022 17.6.5
Bridge to Kubernetes 2022 extension 3.2.20230715.6

**To Reproduce**
1. Click the "Bridge to Kubernetes" debug option in VS 2022
2. Wait a long time and then the timeout error appears
3. Dismiss and view the debug profile and also see an error there

**Expected behavior**
Successful bridging, no timeout exceptions

**Screenshots**
![image](https://github.com/Azure/Bridge-To-Kubernetes/assets/41150696/ce8ded0c-ab42-47d3-93cc-44af65c079ef)
![image](https://github.com/Azure/Bridge-To-Kubernetes/assets/41150696/4dac4023-5fa6-4939-87c8-d3d07bc8f865)

**Logs:**
 - [bridge-library-2023-08-03-09-33-57-49180.txt](https://github.com/Azure/Bridge-To-Kubernetes/files/12249255/bridge-library-2023-08-03-09-33-57-49180.txt)

```[tasklist]
### Tasks
```

**Comment by hsubramanianaks** [comment]
@stevendarby Thanks for raising this issue. Are you using kubelogin ? Because I can see exact error which you got in the kubernetes client for csharp repo and it was raised last week , issue [here](https://github.com/kubernetes-client/csharp/issues/1346). Please let me know.

**Comment by stevendarby** [comment]
@hsubramanianaks I'm not sure - not explicitly. Could it be something I'm using implicitly - how can I tell? FWIW a colleague with the same problem said that using the bridge cli works, it's just the extension with the issue. Hopefully that helps narrow it down.

**Comment by hsubramanianaks** [comment]
@stevendarby Try this command and see if it works ```kubectl config view --minify | grep -q user && echo "Kubelogin is configured"``` , and please let me know what's the result. Thanks.

**Comment by stevendarby** [comment]
@hsubramanianaks I get an error about grep not being installed but that's probably not what you want.
`command: kubelogin` is there under the cluster user if that's what you need to know.
It also says
```
kubelogin is not installed which is required to connect to AAD enabled cluster.

To learn more, please go to https://aka.ms/aks/kubelogin
```

I tried [installing it](https://azure.github.io/kubelogin/install.html#windows) and [setting it up](https://azure.github.io/kubelogin/quick-start.html) but I still have that comment in the config and still get the error bridging/configuring bridging.

**Comment by hsubramanianaks** [comment]
@stevendarby to unblock you can, try setting ```KUBECTL_PROXY=your proxy value``` in your environments before starting bridge in Visual Studio and try a bridge session with this env variable set.  you can refer [here](https://github.com/Azure/Bridge-To-Kubernetes/issues/246#issuecomment-1531144370) for more details. Please let me know how it goes.

**Comment by stevendarby** [comment]
@hsubramanianaks is the proxy value meant to be the cluster server address in the config (also the URL I see on the left when editing the profile in VS)? If so, after doing this, the error is now:

![image](https://github.com/Azure/Bridge-To-Kubernetes/assets/41150696/7c360b83-e125-412e-9e4f-eb887aae843c)

**Comment by hsubramanianaks** [comment]
@stevendarby you have to type kubectl proxy in your terminal and it would give a url which can be set as KUBECTL_PROXY. Example below. 
![image](https://github.com/Azure/Bridge-To-Kubernetes/assets/105889062/771f53e7-a6c5-4c32-b903-041a59d483aa)

Please try and let me know, thank you.

**Comment by stevendarby** [comment]
@hsubramanianaks

1. I ran `kubectl proxy` to get the URL (same as yours).
2. I stopped the proxy (Ctrl+C)
3.  I put this URL the environment variable.#
4. This said it didn't have the right scheme
5. I added http:// in front of it. 
6. This still didn't work.
7. I ran `kubectle proxy` again, leaving it running this time.
8. It works! 🥳 Thank you

I'm a bit unclear on this proxy... I think you just said I needed to put the proxy URL in the environment URL, but is it also the case that I need to run `kubectl proxy` while I bridge? Can you give a brief explanation as to what's going on here, as I didn't have to run `kubectl proxy` before. Is that something the bridge extension did for me before that I have to do manually as a workaround now?

**Comment by hsubramanianaks** [comment]
@stevendarby Yes you have to leave it running, apologies I was not clear in my previous comments. You can read more about it [here](https://kubernetes.io/docs/tasks/extend-kubernetes/http-proxy-access-api/). Kubectl Proxy is http proxy to access your k8s cluster Api's and it is an alternative way to access your k8s clusters. 

After #246 was reported, the fix and env variable was added an alternative way to authenticate your k8s cluster to successfully use bridge to Kubernetes. This helps users with k8s cluster using different OAuth providers, kubelogin etc.. since bridge uses Kubernetes Client for csharp and until they fully support this refer [known issues](https://github.com/kubernetes-client/csharp#known-issues) , there has to be some manual steps to run bridge successfully. Hopefully this helps. Glad to know it worked !!

**Comment by stevendarby** [comment]
Thank you @hsubramanianaks!

I’d been using Bridge to Kubernetes successfully against AKS for a few weeks and then last week I set up AKS afresh and that is when I started having these issues. Do you think it’s because my fresh AKS setup was configured differently to before (eg different auth provider), or was it just coincidentally timed with an update to the extension? That’s something I can’t quite get straight in my head- but to be honest, I don’t mind not fully understanding the issue, just happy it’s working again :smile:

**Comment by stevendarby** [comment]
@hsubramanianaks yep it's working. You can close this issue if you wish. Am I right in thinking for this to be fully fixed (no workaround required), you're waiting for a fix from "Kubernetes Client for csharp", which can then go into the VS extension?

Also, I may be more curious than I implied above, as to why the extension has only stopped working recently. Some colleagues are still using the extension fine without the workaround. A better understanding of where this issue occurs and where it doesn't would be useful for me so I can advise colleagues accordingly.

**Comment by hsubramanianaks** [comment]
@stevendarby Thanks for the reply. Yes, I don't know if ever Kubernetes Client for csharp would support kubelogin scenarios, they are tracking the issue [here](https://github.com/kubernetes-client/csharp/issues/1346) and we can follow up here, only update for Bridge would bump on the dependency which can be done quickly and released.

Kubelogin is a command-line tool that helps you to obtain a Kubernetes authentication token using your existing Kubernetes credentials. It is typically used in situations where you need to authenticate with a Kubernetes cluster from a non-Kubernetes environment, such as a local development machine or a CI/CD pipeline. By using Kubelogin, you can avoid having to manually manage Kubernetes authentication tokens, which can be a time-consuming and error-prone process. 

May be your colleagues are not using kubelogin yet and they are not facing this issue?
