### ISSUE TITLE
Failed to establish a connection. Error: Failed to deploy remote restore job for pod deployment

### ISSUE THREAD

**Issue by alexdauenhauer** [Azure/Bridge-To-Kubernetes#306]
**Describe the bug**
I follow the steps [here](https://learn.microsoft.com/en-us/visualstudio/bridge/bridge-to-kubernetes-vs-code#configure-the-debugger-for-local-tunnel-debugging-with-bridge-to-kubernetes) to debug my test and I get this error
```
Failed to establish a connection. Error: Failed to deploy remote restore job for pod deployment '$NAMESPACE/$POD_NAME' with error: Encountered permissions error. To see which permissions you need to run Bridge To Kubernetes, visit https://aka.ms/bridge-to-k8s-rbac. Error: Forbidden: roles.rbac.authorization.k8s.io "lpkrestorationjob-role-v2" is forbidden: user "$USER" (groups=["redacted" "redacted" "system:authenticated"]) is attempting to grant RBAC permissions not currently held: {APIGroups:["extensions"], Resources:["statefulsets"], Verbs:["get" "list" "update" "patch"]}
```

**Mention the platform you are using**
macOS, VS Code

**To Reproduce**
1. follow steps in instructions
2. run test debugging
3. watch connections try to happen

**Expected behavior**
There would not be an error

**Screenshots**

**Logs:**
 - Please attach logs for Bridge to Kubernetes to triage issues faster, here are the log locations ( Window like C:\Users\Username\AppData\Local\Temp\Bridge To Kubernetes, Linux/Mac like $HOME/tmp/Bridge To Kubernetes or /tmp/Bridge To Kubernetes). Please attach logs relevant to your issue or bug. 

these paths do not exist so I do not know where to find the logs

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: N/A
 - Version: 13.5.1

**Comment by hsubramanianaks** [comment]
@alexdauenhauer Thanks for raising this issue, can you try setting permissions if your cluster RBAC enabled for bridge to work correctly ? Refer [here](https://learn.microsoft.com/en-us/visualstudio/bridge/overview-bridge-to-kubernetes?view=vs-2019#kubernetes-rbac-authorization)

**Comment by alexdauenhauer** [comment]
thank you @hsubramanianaks I don't manage the cluster or have access to add these permissions so I won't be able to follow those steps. I guess we can close this issue then, thanks
