### ISSUE TITLE
Not able to connect to aks cluster

### ISSUE THREAD

**Issue by srinivasmummareddy** [Azure/Bridge-To-Kubernetes#309]
**Describe the bug**
I'm trying to connect to aks cluster using B2K(version-3.2.20230819.1) from vs2022. its going timeout  but if I use kubectl commands its working as expected

**Mention the platform you are using**
I'm using windows 11, Visual studio 2022

**Expected behavior**
Expected to connect to cluster.

**Screenshots**
![image](https://github.com/Azure/Bridge-To-Kubernetes/assets/22257824/439c5d22-66a6-48a1-a7cf-5d9af40dbcb2)

Using the following command
 kubelogin convert-kubeconfig -l azurecli

**Comment by hsubramanianaks** [comment]
@srinivasmummareddy Thanks for raising this issue. Can you share the logs from ```C:\Users\youruserid\AppData\Local\Temp\Bridge To Kubernetes``` ? ex: bridge-mindarocli-*, bridge-* logs. Seems like this is auth  issue to your k8s cluster. There is workaround for this since you are using kubelogin you can try following 

```
1. Open a terminal, type kubectl proxy which would open a proxy between your local machine and your k8s cluster
2. Above commands output a url ex: Starting to serve on 127.0.0.1:8001 etc.. copy ip:port and set environment variable in power shell terminal window $env:KUBECTL_PROXY=http://127.0.0.1:8001
3. now from the same terminal where you set the KUBECTL_PROXY open visual studio ex: devenv.exe to open visual studio from power shell cmd window with environment variable set. 
4. Try debugging using bridge. 
```

Please let me know how it goes, thanks.

**Comment by srinivasmummareddy** [comment]
@hsubramanianaks 
[bridge-mindarocli-2023-09-05-11-01-54-24088.txt](https://github.com/Azure/Bridge-To-Kubernetes/files/12522686/bridge-mindarocli-2023-09-05-11-01-5
[bridge-library-2023-09-05-11-01-55-24096.txt](https://github.com/Azure/Bridge-To-Kubernetes/files/12522690/bridge-library-2023-09-05-11-01-55-24096.txt)
4-24088.txt)

**Comment by srinivasmummareddy** [comment]
@hsubramanianaks  If its the case how I'm able to access the cluster from powershell as my visual studio and terminal are behind the same firewall?

**Comment by hsubramanianaks** [comment]
@srinivasmummareddy this is related to csharp client for kubernetes which bridge uses. So kubectl with kubelogin would work but client is not working and there is an open issue - [here](https://github.com/kubernetes-client/csharp/issues/1346).

**Comment by srinivasmummareddy** [comment]
@hsubramanianaks  any hack to fix this?

**Comment by hsubramanianaks** [comment]
@srinivasmummareddy the only workaround was to set environment variable KUBECTL_PROXY= and use bridge. But that doesn't seem to work for you. can you try without kubelogin ?

**Comment by Ranjit-Kumar-Konjeti** [comment]
I have the same issue cannot connect to the cluster , I am using this c# kubernetes client library .kubeconfigclient.ListNamespacedPod("namespacename"). I tried all the above steps by setting KUBECTL_PROXY and updating the host to http: //<proxyip:8001> and I am not using kube login.  code execution stops at the above line and my visual studio 2022 hangs and I see messages thread exited in the output window. I can get all the details by connecting to cluster using kubectl commands in the terminal window. but not through c# libraray. Please look into this ASAP. @hsubramanianaks

**Comment by hsubramanianaks** [comment]
@Ranjit-Kumar-Konjeti do you use bridge to kubernetes extension in visual studio 2022 or using k8s c# library for your application and facing this issue ? because this thread is specifically for bridge to Kubernetes extension. if it is later please raise an issue in k8s client repo. https://github.com/kubernetes-client/csharp. Thank you.

**Comment by hsubramanianaks** [comment]
@srinivasmummareddy Please feel free to reopen this issue if you need more help. Thank you.
