### ISSUE TITLE
Use kubectl.kubernetes.io/default-container to identify main container

### ISSUE THREAD

**Issue by dominikjeske** [Azure/Bridge-To-Kubernetes#317]
When POD has additional containers bridge to kubernetes has problems to identify main container. I wonder if this label https://kubernetes.io/docs/reference/labels-annotations-taints/#kubectl-kubernetes-io-default-container could be used in container identification logic?

**Comment by hsubramanianaks** [comment]
@dominikjeske thanks for raising this issue. There is an option to provide the container name if you are using the CLI directly with option --container <name of the container>. If you are vscode extension we are working on enhancing this. Here if the PR for it https://github.com/Azure/vscode-bridge-to-kubernetes/pull/71. Please let me know if you want to give a try.

**Comment by hsubramanianaks** [comment]
@dominikjeske Bridge identifies the container based on the following approaches

1. if container name is provided by the user
2. bridge selects the service based on the port/targetPort, code is [here](https://github.com/Azure/Bridge-To-Kubernetes/blob/main/src/library/Utilities/RemoteContainerConnectionDetailsResolver.cs#L370). 
3. Also we are enhancing this logic if you are using vscode extension and will be released soon. PR is [here](https://github.com/Azure/vscode-bridge-to-kubernetes/pull/71).

if you still think we need this enhancement please let us know. Thanks.

**Comment by hsubramanianaks** [comment]
@dominikjeske Please feel free to reopen this issue if you have more questions or issues. Thank you.
