### ISSUE TITLE
Pods in multiple namespaces

### ISSUE THREAD

**Issue by larscliff** [Azure/Bridge-To-Kubernetes#329]
Thank you for this amazing tool.

I would like to clarify one thing: Does Bridge-To-Kubernetes work when I run and debug code that needs to interact with a pod from another namespace?

Let's consider this scenario: I have two namespaces in my cluster. Namespace A contains a Redis pod and its associated service, while namespace B contains a worker pod and its service. I am running the worker's code on my local machine. However, when the worker attempts to connect to Redis (using the 'redis-svc-name.namespaceB' notation), I encounter an error: "StackExchange.Redis.RedisConnectionException: 'It was not possible to connect to the Redis server." 
Is it expected behavior?

**Comment by hsubramanianaks** [comment]
@larscliff Thanks for your compliments. Yes, bridge supports this you need to specify the redis service from namespace A in KubernetesLocalProcessConfig.Yaml , refer [here](https://learn.microsoft.com/en-us/visualstudio/bridge/configure-bridge-to-kubernetes#make-a-service-available) or below. After adding this file , start using bridge redis service will be available from namespace A. Please let me know how it goes. 

```
version: 0.1
env:
  - name: MY_REDIS_SERVICE
    value: $(services:redis.namespaceA)
```

**Comment by esinmy** [comment]
@hsubramanianaks  Thank you, it works! I missed this part of the documentation, sorry.

Currently, I specify Redis address in a static configuration file, like appsettings.json. Is there an easy workaround to use environment variables (coming from KubernetesLocalProcessConfig.Yaml) in this file?

**Comment by larscliff** [comment]
@hsubramanianaks Thank you, it works! I missed this part of the documentation, sorry.

Currently, I specify Redis address in a static configuration file, like appsettings.json. Is there an easy workaround to use environment variables (coming from KubernetesLocalProcessConfig.Yaml) in this file?

**Comment by hsubramanianaks** [comment]
@larscliff if you use option of ``` --use-kubernetes-service-environment-variables``` either via CLI or vscode extension in tasks.json you will have the service available via environment variables. Please let me know for further details.

**Comment by hsubramanianaks** [comment]
@larscliff Please feel free to open this issue again if it doesn't work or if you have any questions. Thank you.
