### ISSUE TITLE
bridgetokubernetes.azurecr.io/lpkremoteagent:1.3.4 not found

### ISSUE THREAD

**Issue by mayong43111** [Azure/Bridge-To-Kubernetes#341]
**Describe the bug**
Error response from daemon: manifest for bridgetokubernetes.azurecr.io/lpkremoteagent:1.3.4 not found: manifest unknown: manifest tagged by "1.3.4" is not found

**Mention the platform you are using**
 $ dsc --version
1.0.20231127.3.

**To Reproduce**
 
1. dsc connect --service myService --local-port 1433 --namespace default

**Comment by hsubramanianaks** [comment]
@mayong43111 Thanks for raising this issue. Are you using B2K via CLI ? If so apologies for this inconvenience, we will fix this asap. Please confirm.

**Comment by mayong43111** [comment]
> @mayong43111 This is now fixed can you please verify and confirm here? Please reinstall the CLI again and try.

thanks a lot.
