### ISSUE TITLE
Failed to Update on Mac + Vs Code - Failed to Load

### ISSUE THREAD

**Issue by Leonardo-Ferreira** [Azure/Bridge-To-Kubernetes#350]
**Describe the bug**
When updating the bridge I get the error of incompatibility between x86_x64 and ARM

**Mention the platform you are using**  
MAC OSX 14.2.1 + VSCode

**To Reproduce**
Try to update kubernetes bridge via VS Code on a ARM Mac 

**Expected behavior**
It updates

**Logs:**
[mindaro-vscode-2024-01-12T15-42-41.344Z.txt](https://github.com/Azure/Bridge-To-Kubernetes/files/13921060/mindaro-vscode-2024-01-12T15-42-41.344Z.txt)

**Desktop (please complete the following information):**
 - OS: MAC OSX
 - Browser: Safari

**Comment by hsubramanianaks** [comment]
@Leonardo-Ferreira Thanks for raising this issue, this is side effect of current release and previous and current release had features to support arm64 clusters and machines. So, one thing you can do to make this work, you have to delete all the files under ```~/Library/Application Support/Code/User/globalStorage/mindaro.mindaro/file-downloader-downloads/*```, it would have three folders bridge, dotnet, and kubectl. Please do ```rm -rf *``` and then reopen vscode which would download all three folders for you and the error would be gone. Apologies for this inconvenience this should be a onetime thing. Please let me know how it goes.

**Comment by Leonardo-Ferreira** [comment]
it worked!
