### ISSUE TITLE
2.0.120240111 for Microsoft Visual Studio 2022	

### ISSUE THREAD

**Issue by Snotax** [Azure/Bridge-To-Kubernetes#352]
When is the new "Bridge to K8s" version available for Visual Studio 2022 ?

The current version for VSCode has a fix in it for debugging "arm" clusters. 
We would really need that in the VSStudio extension aswell. 

When are you planning on updating this Extension ?

**Comment by hsubramanianaks** [comment]
@Snotax Thanks for raising this concern. Usually our release cadence is 2 to 3 days after vscode extension is released. We are planning for a release by next week. we will keep you posted on this.

**Comment by stevendarby** [comment]
@hsubramanianaks probably unlikely but really keen to see if the pending release happens to fix https://github.com/Azure/Bridge-To-Kubernetes/issues/343.

**Comment by hsubramanianaks** [comment]
@stevendarby I highly doubt that, I think your issue is with visual studio installation, because my team was not able to reproduce issue #343. But still it is worth the try, I will be releasing it today. Thank you.

**Comment by stevendarby** [comment]
@hsubramanianaks it’s 3 with the issue vs 2 without in that thread ;)

**Comment by hsubramanianaks** [comment]
@stevendarby I am hoping the latest release will fix this issue #343. Fingers crossed. I tested them using VS 17.8.5 , it worked fine without any issues. are you running 17.8.5 same as mine ?

![image](https://github.com/Azure/Bridge-To-Kubernetes/assets/105889062/83ec89c4-2758-4b6d-91aa-c8a2e5bab40e)

**Comment by hsubramanianaks** [comment]
@Snotax @stevendarby This is released to marketplace, please verify and let us know for any issues. Thanks for the patience.

**Comment by Snotax** [comment]
@hsubramanianaks  Thank you very much. First tests seemd positive. I'm gonna close this!
