### ISSUE TITLE
Traffic via tunnel does not reach to pod in Windows10 vscode

### ISSUE THREAD

**Issue by smbd** [Azure/Bridge-To-Kubernetes#36]
**Describe the bug**
In Windows10 box, when setting up Bridge to Kubenetes is finished, tunnels to pods are created.
But connection is time out.

**Mention the platform you are using**
vscode

**To Reproduce**
Trying python app sample: https://microsoft.github.io/AzureTipsAndTricks/blog/tip365.html
1. '3. Click on the Run and Debug configuration "Python: Current File with Kubernetes". '
2. wait setup is completed and execute python debugger automatically.
3. An error is occurred, "Failed to connect to Redis"

**Expected behavior**
Succecssfully connect to backend redis server

**Screenshots**
![image](https://user-images.githubusercontent.com/142148/188032372-b484e302-a516-44e3-a554-f6efb0d6d97d.png)

**Desktop (please complete the following information):**
 - OS: Windows10 21H1
 - Browser: no browser
 - Version: VS Code v1.70.2 - Extension v1.0.120220817

**Additional context**
After setup is completed, tunnels is maked, and connections is accepted, but no response. (port 6379 is redis's)
```
$ netstat -an | grep 127.1.1.
  TCP         127.1.1.1:6379         0.0.0.0:0              LISTENING
  TCP         127.1.1.2:80           0.0.0.0:0              LISTENING
```
But no response
```
$ redic-cli -h 127.1.1.1
127.1.1.1:6389> INFO
(No response...)
```

**Comment by hsubramanianaks** [comment]
@smbd Hi, I am unable to replicate this issue in my local, I am able to debug with the above error. If you are trying with an example, you can try with sample app from below link - https://github.com/Azure/Bridge-To-Kubernetes/tree/main/samples/todo-app
Also did you try with or without isolation? Please let me know. Thank you for your patience.

**Comment by smbd** [comment]
I tried without isolation.

**Comment by elenavillamil** [comment]
Hi @smbd, we will be closing this ticket next week due to lack of inactivity. Please feel free to re-open as needed. Thank you.
