### ISSUE TITLE
Ubuntu 22.04 - Failed to update dependencies: No usable version of libssl was found

### ISSUE THREAD

**Issue by sabbour** [Azure/Bridge-To-Kubernetes#42]
**Describe the bug**
Unable to proceed with installing dependencies for the Bridge to Kubernetes extension for Visual Studio Code, hence I'm blocked from configuring the extension to connect to my Kubernetes cluster. Seems to be related to https://forum.unity.com/threads/workaround-for-libssl-issue-on-ubuntu-22-04.1271405/

**Mention the platform you are using**
Visual Studio Code extension running on WSL2 and Ubuntu 22.04.

**To Reproduce**
1. Install the extension on Visual Studio Code
2. Follow the [tutorial](https://docs.microsoft.com/en-us/visualstudio/bridge/bridge-to-kubernetes-sample?source=recommendations) to create a namespace for the app and deploy it,
3. Run `npm install`
4. Open the Command Palette and run **Bridge to Kubernetes: Configure**
5. There is a missing dependency on "libssl". Running "Retry Dependency Update" doesn't fix the problem.

**Expected behavior**
Proceed to select the Kubernetes service to redirect.

**Screenshots**

![This action requires dependencies that are not available yet. Please look at the "Kubernetes" item in the status bar for more information.](https://user-images.githubusercontent.com/103856/188751822-5be54177-17e9-4525-9566-b9f612e60989.png)
![Failed to update dependencies: No usable version of libssl was found](https://user-images.githubusercontent.com/103856/188751851-67efb3bd-6c7b-438a-a601-efa6000366bc.png)

**Additional context**
See this issue: https://github.com/microsoft/mindaro/issues/327
Ubuntu 22.04 (via WSL): has OpenSSL 3 installed by default
```
openssl version -v
OpenSSL 3.0.2 15 Mar 2022 (Library: OpenSSL 3.0.2 15 Mar 2022)
```
Looks like Bridge to Kubernetes is build using .NET Standard 2.1 which only supports older versions of OpenSSL. .NET 5 requires OpenSSL 1.x. Newer distro versions such as Ubuntu 22.04 use OpenSSL 3 and not OpenSSL 1.x (see https://github.com/dotnet/core/blob/main/release-notes/5.0/5.0-supported-os.md)

So, Bridge will need to be rebuilt using .NET 6+ to support a newer distro that only offers OpenSSL 3, or another workaround to install OpenSSL 1.x will need to be provided (see https://github.com/dotnet/core/issues/4749#issuecomment-1200245422)

**Comment by sabbour** [comment]
Related? https://github.com/dotnet/core/issues/4749#issuecomment-1200245422

**Comment by sabbour** [comment]
cc: @elenavillamil @hsubramanianaks

**Comment by sabbour** [comment]
Installing OpenSSL 1.1.1 via the commands below acts as a workaround:
```
wget https://www.openssl.org/source/openssl-1.1.1c.tar.gz
tar -xzvf openssl-1.1.1c.tar.gz
cd openssl-1.1.1c
./config
make
sudo make install
export LD_LIBRARY_PATH="/usr/local/lib"
```

**Comment by JohnGalt1717** [comment]
I'm getting this on Ubuntu 22.04.  Replacing OpenSSL isn't a real viable solution because it has issues with security and other stuff depends on the newer version. Is there a version of Bridge to K8s that works with 3.0.2?

**Comment by elenavillamil** [comment]
This will be fully address once dotnet6 release goes out this month.

**Comment by hsubramanianaks** [comment]
Dotnet 6 is deployed to production, @sabbour can you test once and close this issue ?

**Comment by sabbour** [comment]
Yes, I just tested it and it works. Closing. Thanks!
