### ISSUE TITLE
Add support for Mac M1 Arm64

### ISSUE THREAD

**Issue by shivam-sood89-admin** [Azure/Bridge-To-Kubernetes#43]
**Is your feature request related to a problem? Please describe.**

**Mention what platform you want to support the new feature**
Mention what platform you would like the feature request to live in (oss, vscode) and select the proper label.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by qpetraroia** [comment]
Hi @shivam-sood89-admin,

Can you please add more detail? Thanks!

**Comment by elenavillamil** [comment]
Close due to lack of details and response. Please feel free to re-open as needed.

**Comment by dklesev** [comment]
@elenavillamil  pls reopen
Either the default install within vscode works nor the install scripts helps
There is just no arm64 built version available as it seems to be
![image](https://user-images.githubusercontent.com/6021382/227814975-53a6b70a-b612-4655-8f08-e3096387a2c6.png)

(tried on Apple M2)
