### ISSUE TITLE
Use Azure Container Application with Bridge To Kubernetes

### ISSUE THREAD

**Issue by BartNetJS** [Azure/Bridge-To-Kubernetes#50]
Is it possible to use Bridge To Kubernetes with ACA?

**Comment by sabbour** [comment]
Hi @BartNetJS , this is not currently supported nor it is on the roadmap. What would be the scenario you're looking for? the underlying Kubernetes environment of Azure Container Apps is not exposed.
cc: @kendallroden FYI.

**Comment by BartNetJS** [comment]
Hi Sabbour, 

I’m investigating a greenfield project where we gone use DAPR as distributed application runtime.
For the infrastructure there are 2 options.
AKS or ACA.
ACA is interesting because it has native DAPR support.
And ACA is much more maintainable than AKS.
Also, the serverless characteristics of ACA is a plus.

On the other hand, I’m looking into the way how developers are gone develop the microservices.
The preferred choice is running the other microservice in a development cluster in AKS or ACA.
And use Bridge to Kubernetes to have a virtual local experience for the developer.

Does that make any sense to you?

**Comment by qpetraroia** [comment]
Thanks for this @BartNetJS,

We will discuss this with the team.

**Comment by BartNetJS** [comment]
@hsubramanianaks We decided to use AKS
