### ISSUE TITLE
CLI support for Bridge

### ISSUE THREAD

**Issue by hsubramanianaks** [Azure/Bridge-To-Kubernetes#54]
Bridge To Kubernetes can be used as a standalone CLI tool since many customers want this feature

- Download bridge via CURL will be one of the easy and best options. 
- Download bridge stable version, this can be done via following command ``` curl -LO $(curl -L -s https://aka.ms/bridge-lks | jq -r '.linux.url')  ```
- Download a particular version for linux operating system, this can be also done via CURL  ``` curl -LO  https://bridgetokubernetes.azureedge.net/zip/<version>/lpk-<arch>.zip ```
- write a shell script and power shell script to download them so it will be easier for the user to just run this script. 
- Update the public documentation for this which gives more adoption towards this tool.
- Update the help menu for the CLI tool
@elenavillamil  @Tatsinnit @gambtho @qpetraroia @sabbour  your thoughts please.

**Comment by elenavillamil** [comment]
This looks good, I do have a couple notes:

1. I believe aka.ms is internal to microsoft, we will need different url for stable download.
2. Did you go to SDL office hours and verify this approach is SDL compliant?
3. In addition to public documentation, let's also make sure the help message for the cli is ready for public download.

**Comment by hsubramanianaks** [comment]
> This looks good, I do have a couple notes:
> 
> 1. I believe aka.ms is internal to microsoft, we will need different url for stable download.
> 2. Did you go to SDL office hours and verify this approach is SDL compliant?
> 3. In addition to public documentation, let's also make sure the help message for the cli is ready for public download.

Yes, updated the url. Yes, it is SDL compliant since it is downloading from storage account and uses TLS 2.0. 
Correct we need to update help menu for the CLI.

**Comment by Tatsinnit** [comment]
> > This looks good, I do have a couple notes:
> > 
> > 1. I believe aka.ms is internal to microsoft, we will need different url for stable download.
> > 2. Did you go to SDL office hours and verify this approach is SDL compliant?
> > 3. In addition to public documentation, let's also make sure the help message for the cli is ready for public download.
> 
> Yes, updated the url. Yes, it is SDL compliant since it is downloading from storage account and uses TLS 2.0. Correct we need to update help menu for the CLI.

☕️💡🥷 Please note: `aka.ms` is visible in internet and it is a `hyperlink/URL shortener` from Microsoft

* https://docs.microsoft.com/en-us/answers/questions/682205/what-is-httpsakams-why-is-this-firewalled.html#:~:text=https%3A%2F%2Faka.ms%2F...%20is%20a%20hyperlink,create%20this%20short%20hyperlinks%2FURLs. 

Thanks, so you can keep `aka.ms` in fact it is used in many places around Microsoft docs.

Rest sounds like awesome idea. 🎊

**Comment by ajaffie** [comment]
It would be really nice if the CLI were available for install through winget, but I realize that is a relatively involved process.
Making releases available in this repo's Releases would also be really helpful though.

**Comment by elenavillamil** [comment]
I would be curious to get community input on what is the usage for this feature. Mostly interested to know if most people asking for this are looking at using it in linux/mac or if there are Windows users that would want this feature as well (to use on windows not through WSL).

**Comment by ajaffie** [comment]
I use the CLI on windows exclusively because I don't use vscode or VS.

**Comment by hsubramanianaks** [comment]
@qpetraroia this feature is merged and is available to customers, we can further enhance this in next features to be installed by Package Managers like choco, yum, brew etc. as an enhancement to get more adoption.

**Comment by hsubramanianaks** [comment]
Closing this since the PR is merged.
