### ISSUE TITLE
The JSON value could not be converted to k8s.Models.V1ServiceStatus

### ISSUE THREAD

**Issue by elenavillamil** [Azure/Bridge-To-Kubernetes#55]
**Describe the bug**
Bridge to Kubernetes sometimes fails with error: "An unexpected error occurred: 'The JSON value could not be converted to k8s.Models.V1ServiceStatus". Restarting VSCode will help and fix this issue. From metrics this started happening around August 07th.

**Mention the platform you are using**
All (Linux, Windows, Mac). VSCode.

**To Reproduce**
It happens sporadically when you start debugging using bridge.

**Expected behavior**
This error should not happen.

**Comment by ajaffie** [comment]
Not 100% on this but it seems to happen when the routingmanager deployment is being created. Simply retrying the command has been successful for me. This happens for CLI and Visual Studio as well.

**Comment by elenavillamil** [comment]
This is happening during routing manager deployment inside function call to DeleteNamespacedServiceAsync which is inside CreateOrReplaceV1ServiceAsync

**Comment by elenavillamil** [comment]
Fix for this got deployed today. I. will keep an eye on our internal metrics and re-open if this still reproduces.
