### ISSUE TITLE
Multiple "proxy" pods running, blocking a new debug session

### ISSUE THREAD

**Issue by Eneuman** [Azure/Bridge-To-Kubernetes#56]
Using Visual Studio Professional 2021 with latest extension.

If you stop your debug session and then start it while your previous pod is being restored by the "restore" pod, you sometimes ends up with two "proxy" pods running, both theese pod keeps craching and the only way to fix this is to deploy you original pod from scratch.

I think I have figured out what is happening and how to fix this.
The problem seems to be that sometimes a "proxy" pod is created that tries to proxy the already existing proxy pod.

How to fix this:
If you try to start debugging when there are two pods running, you will get a error message from the extension, telling you that  "... is currently backed by two pods. Please try again later".

If this code were to look at the tags set on thoose pods, it would see that both pods are "proxy" pods, created by B2K. It could then just remove both theese pods and restore the original pod, before trying to setup a new debug session.

It's easy to reproduce so let me know if you need any logs.

**Comment by elenavillamil** [comment]
Hi @Eneuman, before starting a new Bridge connection you should always wait for previous connection to be fully restored. If you start a new connection before previous one is properly restored. There are several things that go wrong when a new session is connection before previous one is cleaned up. For bridge to try an clean up that state is too complicated, but what we can do is add a check when bridge is connecting and if it sees <your service>-restore pod is present then show error to the user and prevent connection.

**Comment by Eneuman** [comment]
@elenavillamil A check would be great. Right now i'm using k9s to see when the restore pod has finished it's job. But sometimes I forget to check and then I have to redeploy the pod from the devops pipeline, witch takes time.

**Comment by Eneuman** [comment]
> For bridge to try an clean up that state is too complicated, but what we can do is add a check when bridge is connecting and if it sees -restore pod is present then show error to the user and prevent connection.

After having a second look at this, maby using kubernets "roullout undo" could be a nice way of handling this.

Running this command `kubectl rollout history deploy myservice` shows all changes made to the service.

```
REVISION  CHANGE-CAUSE
810       <none>
811       <none>
813       <none>
815       <none>
817       <none>
819       <none>
821       <none>
823       <none>
825       <none>
827       <none>
828       <none>
```


If the B2K deployment would set the "CHANGE-CAUSE" to "B2K", then it could loop through the revisions to find the latest not marked with B2K and then do a `kubectl rollout undo deploy myservice--to-revision=X`
and after that, delete and restore pod.

Doing this manually seems to work.

**Comment by elenavillamil** [comment]
Closing as this was address  with 0216 release. Now if user tries to start bridge when Restore pod is present bridge wont allow it. If restore pod ever gets stuck/crashloop user can always delete the restore job (kubectl get all and then kubectl delete <restore job name from previous command>)
