### ISSUE TITLE
Deploy RoutingManager to K8S without using Visual Studio extension

### ISSUE THREAD

**Issue by vitaly-pavluk** [Azure/Bridge-To-Kubernetes#57]
I want to deploy RoutingManager without installing and running the VisualStudio Bridge2Kubernetes extension. 

I use AKS to host microservices and rely on the Routing manager that is auto-provisioned by the VS extension but I don't want to install VS B2K extension and run it each time I set up a new K8S namespace.

Before I deployed RoutingManager from the OLD B2K repo https://github.com/microsoft/mindaro/blob/master/routingmanager.yml
but since it uses a Docker image with old code that does not work in K8s anymore I have to use VS extension to provision it.

The new Bridge-To-Kubernetes repo does not have **routingmanager.yml** file or at least I could not find it there.

Could you please share with me how I can find the YAML file with RoutingManager K8S resources? 

If no RoutingManager YAML file exists how can I use parts of the VS extension - e.g. EndpointManager.exe,  Bridge.exe, or any other part of VS extension running in the terminal to deploy the RoutingManager service?

Thank you in advance.

**Comment by scp-mb** [comment]
That old chart should work in general, just update the image to point to the new location in this document for `routingmanager` https://github.com/Azure/Bridge-To-Kubernetes/tree/main/deployment#release-1
