### ISSUE TITLE
Some environment variables are not set in the deployment.yaml

### ISSUE THREAD

**Issue by qucc** [Azure/Bridge-To-Kubernetes#58]
I search the whold repo by keyword 'TODOS_DB_SERVICE_HOST',   but i can not find any place to set this environment variable .
Environment.GetEnvironmentVariable("TODOS_DB_SERVICE_HOST") 
Environment.GetEnvironmentVariable("TODOS_DB_SERVICE_PORT")

**Comment by qpetraroia** [comment]
Hi @qucc. 

Why are you trying to set this env variable?

**Comment by elenavillamil** [comment]
Its part of one of the todo examples. It is used so the application knows what DB it is connecting to. You have to set that environment variable to your db host value before starting the sample application. Setting environment variables is different depending on the OS, For example in [linux](https://www.thegeekstuff.com/2012/07/linux-export-command-examples/#:~:text=1%20View%20all%20the%20Current%20Exported%20Variables.%20Use,read%20by%20bash%2C%20if%20~%2F.bash_profile%20or%20~%2F.bash_login%20exists.%E2%80%9D)

**Comment by elenavillamil** [comment]
@qucc, please let us know if this is still an issue or if it can be closed. If it is still an issue please provide details on what exactly is the issue you are having.

**Comment by elenavillamil** [comment]
Hi, closing this due to lack of response. Please, feel free to re-open if needed. Thank you.
