### ISSUE TITLE
Debug Pod from Kuberentes extension integration fails

### ISSUE THREAD

**Issue by elenavillamil** [Azure/Bridge-To-Kubernetes#59]
Version information
VSIX build number: 120220915
Platform: Windows, Mac and Linux
Cluster region: East US
Kubernetes version: 1.22.11
VS Code version: 1.64.0-insider

Steps to reproduce:

Follow [test readme] (https://github.com/Azure/Bridge-To-Kubernetes/blob/main/tests/manual/BridgeToKubernetes.md#k8s-integration) step 13 in that linked section is the one failing.

1. Setup todo-app sample application (see [instruction](https://devdiv.visualstudio.com/DevDiv/_git/Mindaro-Connect?path=/tests/manual/BridgeToKubernetes.md&version=GBmain&anchor=setup-vscode))
2. Debug the pod.
![image](https://user-images.githubusercontent.com/4663400/191041136-d1449203-dcd5-48f8-8ef6-01d480bec6e8.png)

4. Fails with error:
![image](https://user-images.githubusercontent.com/4663400/191041185-b92ddb32-279e-4256-9637-6e444cf55d28.png)

**Comment by hsubramanianaks** [comment]
vscode tasks.json is stripping off the pod's name which is causing this, until this can be fixed Joyer can follow a workaround to edit the tasks.json with correct full name of the pod to get it working. 
Before:
<img width="911" alt="image" src="https://user-images.githubusercontent.com/105889062/191793781-5dfd2da5-dbe4-4a3e-82df-88d81f4ff0b7.png">

After editing it to correct full name of the pod:

<img width="913" alt="image" src="https://user-images.githubusercontent.com/105889062/191793909-8bd34cd5-1cf1-4d1c-8309-2301006ef543.png">

**Comment by Tatsinnit** [comment]
☕️💡thank you for this, closing this for now, Main PR for this is closed hence closing it, if anything else we can always reopen it.
