### ISSUE TITLE
Can't access services with enabled Microsoft Defender on Mac M1

### ISSUE THREAD

**Issue by AKhoria** [Azure/Bridge-To-Kubernetes#68]
**Describe the bug**
Can't use bridge to kubernetes with enabled MS Defender - not able to call services(using dns/direct ip)

**Mention the platform you are using**
macOS, VSCode.

**To Reproduce**
Steps to reproduce the issue:
1) Enable Microsoft Defender on MAC M1
2) Run Bridge to kubernetes 
3) Try to access any service forwarded from remote cluster, eg:
_Service 'frontend' is available on 127.1.1.4:8000_
```
curl 'http://frontend:8000/path'
curl: (52) Empty reply from server

curl 'http://127.1.1.4:8000/path'
curl: (52) Empty reply from server
```

after removing MS Defender I'm able to request service

**Expected behavior**
MS Defender doesn't affect Bridge to kubernetes, or there is a way to add an exception which mitigates the problem

**Desktop (please complete the following information):**
 - macOS Monterey 12.5.1 

**Additional info**:

Mitigation attempts:
- Tried to exclude EndpointManager and dsc processes and the whole binaries folder in Defender - didn't help
- Tried to run dsc as root  - didn't help either 

Result of investigation:
- /etc/hosts contains necessary records
- dsc is listening on the right ip/ports
- EndpointManager successfully enables port forwarding
- Didn't find anything suspicious in logs: bridge-endpointmanager-.txt, bridge-mindarocli-.txt, bridge-library-.txt(ready to provide f logs by request)
-Tried to call service directly: 127.1.1.4:8000, 127.1.1.4:55062 - no luck
-When click "Disconnect from current session" in VSCode have an exception: **Disconnecting from cluster failed: Error: socket hang up**

Managed to debug DSC locally, noticed that when Defender is enabled channel created [here](https://github.com/Azure/Bridge-To-Kubernetes/blob/1d363ab57a95556aae12ec27eb9825a0855261e6/src/common/DevHostAgent/DevHostAgentExecutorClient.cs#L180) almost immediately closed. ` So, it looks like defender cut Port forwarding between DSC and Agent in the cluster

**Comment by AKhoria** [comment]
@elenavillamil here is the code which can be useful for investigation - it localise the issue. Looks like something weird happens when we use aliases(EndpointManager) + Defender + stream.ReadAsync in mac, maybe deadlock(although I didn't find anything suspicious during debug).
Probably that's issue with Defender not the Bridge itself

To reproduce the issue:
- Run `sudo /sbin/ifconfig lo0 alias 127.1.1.1 netmask 255.255.255.255`
- Run program below and call `curl http://127.1.1.1:8001/`
The execution should stuck with enabled Defender and successfully executed without it

`using System.Net;
using System.Net.Sockets;
// 127.0.0.1 works well!!!
var ip = IPAddress.Parse("127.1.1.1");
var port = 8000;
Console.WriteLine("Run this command first");
Console.WriteLine($"sudo /sbin/ifconfig lo0 alias {ip} netmask 255.255.255.255");
var _tcpListener = new TcpListener(ip, port);
_tcpListener.Start();
Console.WriteLine($"Listen:{ip}:{port}");
while (true)
{
    try
    {
        var connection = await _tcpListener.AcceptTcpClientAsync();
        var stream = connection.GetStream();
        byte[] buffer = new byte[40960];

        // The line below hangs forewer with enabled Defender!!!!!
        int cRead = await stream.ReadAsync(buffer, 0, buffer.Length, CancellationToken.None);
        Console.WriteLine($"Read successfully: {cRead}");
        // Console.WriteLine(System.Text.Encoding.Default.GetString(buffer));
    }
    catch
    {
        Console.WriteLine("Error");
    }
}`

**Comment by sabbour** [comment]
Are there any warnings/logs in Microsoft Defender?

**Comment by AKhoria** [comment]
No, we opened ticket for MS Defender as well, because now it's clear that Defender somehow blocks reading(or maybe sending) data through tcp connection which is opened on loopback IPs !=127.0.0.1. And, as those loopback IPs mechanism are the cornerstone of Bridge-to-kubernetes, it blocks communication with remote cluster

**Comment by elenavillamil** [comment]
@AKhoria thank you for the great details and investigation. Did you get any luck with the ticket on MS defender? I know on windows it will give pop up asking if you want to allow traffic. Maybe they are missing something similar on Mac? 

I am going to go ahead and close this issue since it is not really and issue on bridge (as you mention it is bridge core logic the ability to forward traffic if that is cut out, then it is expected that things wont work). But please feel free to re-open if anything changes and there is anything we can do on our end.
