### ISSUE TITLE
Unable to connect to TKE (Tencent Kubernetes Engine) cluster using VS2022 plugin

### ISSUE THREAD

**Issue by Cheongroach** [Azure/Bridge-To-Kubernetes#73]
**Describe the bug**
Hi, I am getting started with [Tutorial](https://learn.microsoft.com/en-us/visualstudio/bridge/bridge-to-kubernetes-vs) and I use the deployment & code example in [https://github.com/Microsoft/mindaro](https://github.com/Microsoft/mindaro). I have configued to the service, allowed the EndpointManager to run in Elevation. But every time it ends up with a dialog: "

**Mention the platform you are using**
Mention what platform you are using (oss, vscode) and pick the corresponding label.
Visual Studio Professional 2022 Preview (17.4.0 Preview 1.0) with *Bridge to Kubernetes 2022* (3.0.20220912.3) on Windows 10 Pro 21H2

**To Reproduce**

Step 1: Install the Plugin, download the code on the disk and make cluster ready. 

Step 2: Click "Bridge to Kubernetes" and Connecting to service

Step 3: Elevation Require

Step 4: Error is shown: 'Cannot establish the Connection to Cluster'

**Expected behavior**
I can access to the cluster to debug in it.

**Screenshots**

![Connecting to service](https://user-images.githubusercontent.com/20296441/195291382-b8dce0ad-4f02-4e63-8cc4-05234bdfb111.png)

![Elevation Require](https://user-images.githubusercontent.com/20296441/195292218-2221ad1f-de5b-454a-b394-035aac8b4f57.png)

(Cannot establish the Connection to Cluster)
![image](https://user-images.githubusercontent.com/20296441/195292682-1210dec5-a135-43b8-aa43-229fae7fa227.png)

**Comment by sabbour** [comment]
Is the kubeconfig context configured properly to connect to the cluster? Is there some sort of IP whitelisting needed on TKE to allow remote connections?

**Comment by elenavillamil** [comment]
@Cheongroach, we are closing this entry due to lack of response, but please feel free to re-open and provide additional context if you are still facing this issue. Thank you!
