### ISSUE TITLE
Running BTK without elevated privileges on local machine

### ISSUE THREAD

**Issue by faithdoub** [Azure/Bridge-To-Kubernetes#75]
At my company, Developers have to request local admin on their machines and these requests get reviewed.  Unfortunately this is a barrier to using BTK.

If a User has write privileges to the HOSTS file, would they still need to be local admins?

Is there an alternative to the local admin requirement?  I saw "Environment variables in source code" in https://learn.microsoft.com/en-us/visualstudio/bridge/kubernetes-environment-variables but in our case the Service is being invoked from an Ingress.

Thank you.

**Comment by elenavillamil** [comment]
Have you tried using that setting with your set up? If you have and it is failing can you share more details so we can replicate the issue as well as logs?

Thank you!
Elena

**Comment by elenavillamil** [comment]
Hi, we will be closing this ticket next week due to lack of activity. Please feel free to re-open if this becomes an issue again.
