### ISSUE TITLE
Windows + Docker Desktop (Kubernetes) + Bridge = Docker desktop stops on vs code attempt to debug

### ISSUE THREAD

**Issue by JohnGalt1717** [Azure/Bridge-To-Kubernetes#77]
**Describe the bug**
Windows + Docker Desktop (Kubernetes) + Bridge = Docker desktop stops on vs code attempt to debug

Immediate after terminal logs show "Container port .. is available at localhost:null." docker desktop shutsdown entirely and everything else that bridge to kubernetes does fails. (i.e. mapping volumes)

**Mention the platform you are using**
Windows 11 (latest) + VS Code (latest) + Docker Desktop (latest)

**To Reproduce**
1. Add the default bridge to kubernetes debug setup from an existing project
2. Run the debug.
3. See error

**Expected behavior**
Should run properly and not shut down docker desktop on startup.

**Screenshots**
Container port 5017 is available at localhost:null.
Downloading volume 'identity-encryption' from '/certificates/identity-encryption' ...
Downloading from '/certificates/identity-encryption' ...
Download failed with error: An error occurred while sending the request.
Retrying ...

![image](https://user-images.githubusercontent.com/1868147/196747880-cf97aa36-83eb-4d7a-8c93-6192f42eb8e1.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Edge
 - Version Latest mainline

**Additional context**
I have a KubernetesLocalProcessConfig.yaml that maps a bunch of environment variables if that matters.

Here's my tasks:

```
        {
            "label": "bridge-to-kubernetes.contacts.resource",
            "type": "bridge-to-kubernetes.resource",
            "resource": "contacts",
            "resourceType": "service",
            "ports": [
                0
            ],
            "targetCluster": "pltfrmd",
            "targetNamespace": "pltfrmd",
            "useKubernetesServiceEnvironmentVariables": false
        },
        {
            "label": "bridge-to-kubernetes.contacts.compound",
            "dependsOn": [
                "bridge-to-kubernetes.contacts.resource",
                "build_contacts"
            ],
            "dependsOrder": "sequence"
        },

```

Here's my launch configuration:

```
        {
            "name": "Contacts with Kubernetes",
            "type": "coreclr",
            "request": "launch",
            "preLaunchTask": "bridge-to-kubernetes.contacts.compound",
            "program": "${workspaceFolder}/Services/Contacts/bin/Debug/net7.0/Contacts.dll",
            "args": [],
            "cwd": "${workspaceFolder}/Services/Contacts",
            "stopAtEntry": false,
            "env": {
                "ASPNETCORE_ENVIRONMENT": "Development"
            }
        },


```

The image attached comes up before it tries. Of course, 443 is used by the ingress on the  cluster and of course has to be used by the cluster, so I'm not sure what this means and why I'd be getting this error message.

**Comment by elenavillamil** [comment]
Hi,

From documentation [here](https://learn.microsoft.com/en-us/visualstudio/bridge/overview-bridge-to-kubernetes) under section "Establishing a connection":
"Starts running and debugging your code on your development computer. If necessary, Bridge to Kubernetes frees required ports on your development computer by stopping services or processes that are currently using those ports."

So from your comment it seems one of the services that will run locally during debugging uses port 443, but from the image, docker on your machine is running in that same port . If you click continue in that prompt bridge will kill the service running in your local machine using that port (to free the port). In this case it is docker, if bridge is killing docker it would explain why things stop working after that. Is it possible for you to configure docker to use different port? Or to configure the service in the cluster to different port?

If above suggestion do not help unblock you, could you paste the full output when you start bridge connection?

Thank you!
Elena

**Comment by elenavillamil** [comment]
Hi @JohnGalt1717 we will be closing this ticket next week due to lack of activity. Please feel free to re-open if still as issue in the future. Thank you.

**Comment by JohnGalt1717** [comment]
Go ahead. I gave up and use a competitive product that works properly now.  Thanks anyway.
