### ISSUE TITLE
Not the expected error message when the schema is not valid

### ISSUE THREAD

**Issue by JoyerJin** [Azure/Bridge-To-Kubernetes#79]
**Describe the bug**
Not the expected error message when the schema is not valid

**Mention the platform you are using**
Windows, VS 2022

**To Reproduce**
1. Open samples\todo-app\database-api\databaseApi.csproj project with VS 2022
2. Create a new file at the root of the project called KubernetesLocalProcessConfig.yaml

> 1. Right click 'Add' -> 'New Item' on solution explorer
> 2. Scroll down to 'YAML File', and enter 'KubernetesLocalProcessConfig.yaml'

3. Add the following content to this file and save:
```
version: 50.0
env:
    - name: FOO
      value: bar
```
4. Select Container in Kubernetes option from the debug dropdown menu.
5. Select the start button next to Bridge to Kubernetes. In the Create profile for Bridge to Kubernetes dialog box, enter the following values:

> Select your cluster name.
> Select todo-app for your namespace.
> Select database-api for the Service to redirect.
> Select the same URL you used previously to launch your browser.

6. Select Save and debug
7. See error: A connection to the cluster couldn't be established.
![image](https://user-images.githubusercontent.com/116236375/196836585-1158e402-cdff-4d71-b8d3-61cb28b3927f.png)

**Expected behavior**
Bridge to Kubernetes fails, with an error message in the output window like "Bridge to Kubernetes process config file is using an unsupported version"

**Screenshots**
![image](https://user-images.githubusercontent.com/116236375/196836585-1158e402-cdff-4d71-b8d3-61cb28b3927f.png)

**Additional context**
Low priority

**Comment by hsubramanianaks** [comment]
@cxznmhdcxz Can you check if this is still happening and if it happens can you grab the logs please ?
