### ISSUE TITLE
NullReferenceException when service doesn't have any backing deployments/pods.

### ISSUE THREAD

**Issue by giulianob** [Azure/Bridge-To-Kubernetes#80]
**Describe the bug**
NullReferenceException when service doesn't have any backing deployments/pods.

**Mention the platform you are using**
VSCode

**To Reproduce**
1. Create a kubernetes service without any pods. For example, a selector that doesn't match any pods.
2. Start bridge in VS Code

**Expected behavior**
Bride should work, throws the following instead:
> 2022-10-21T17:37:03.3030407Z | Library | ERROR | Logging handled exception: System.NullReferenceException: {"ClassName":"System.NullReferenceException","Message":"Object reference not set to an instance of an object.","Data":null,"InnerException":null,"HelpURL":null,"StackTraceString":"   at Microsoft.BridgeToKubernetes.Library.Connect.WorkloadInformationProvider._CollectServicesToRouteAsync(String workloadNamespace, IEnumerable`1 services, CancellationToken cancellationToken)\r\n   at Microsoft.BridgeToKubernetes.Library.Connect.WorkloadInformationProvider.GetReachableEndpointsAsync(String namespaceName, ILocalProcessConfig localProcessConfig, Boolean includeSameNamespaceServices, CancellationToken cancellationToken)\r\n   at Microsoft.BridgeToKubernetes.Library.ManagementClients.ConnectManagementClient.<>c__DisplayClass19_0.<<GetElevationRequestsAsync>b__0>d.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Microsoft.BridgeToKubernetes.Library.ManagementClients.ManagementClientExceptionStrategy.RunWithHandlingAsync[T](Func`1 func, FailureConfig failureConfig)","RemoteStackTraceString":null,"RemoteStackIndex":0,"ExceptionMethod":null,"HResult":-2147467261,"Source":"Microsoft.BridgeToKubernetes.Library","WatsonBuckets":null}

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Brave
 - Version: 1.4, Chromium 106

**Comment by elenavillamil** [comment]
Can you tell us more about your scenario? Currently Bridge will only work if the service being debug has one pod with a single container running in it. Thank you!

**Comment by sabbour** [comment]
I think we should handle this case gracefully instead of throwing a NullReferenceException.

**Comment by elenavillamil** [comment]
Hi @giulianob, we are closing this entry due to lack of information. Please feel free to re-open and provide additional information if this is still an issue.
