### ISSUE TITLE
Support for Private Registries

### ISSUE THREAD

**Issue by yehia2amer** [Azure/Bridge-To-Kubernetes#83]
We're getting an "ImagePullBackOff" for the routing manager pod as well as the others due to a corporate proxy.
It would be great to have support for downloading these images from our private registry (such as Artifactory) and being able to add a prefix to the image (e.g. PRIVATE_REPO/bridgetokubernetes.azurecr.io/lpkremoteagent or PRIVATE_REPO/lpkremoteagent)

Much thanks in advance!

Referencing this issue : https://github.com/microsoft/mindaro/issues/147

**Comment by elenavillamil** [comment]
Hi @yehia2amer, we are investigating this internally. We will reach to previous developers to get more details and get back to you. Thank you!

**Comment by yehia2amer** [comment]
Great, Thanks for the update @elenavillamil

That is the code block that takes hardcoded Registry uri:

https://github.com/Azure/Bridge-To-Kubernetes/blob/9b82b5b47a24f4ec5d4d6eaa4d2610eb0dadde74/src/library/ImageProvider.cs#L23-L30

Thinking of creating a pull request with method to check if there is an env-variable for a private registry and if not fall back to the defaults, are pull requests accepted in here and is that a good idea?

**Comment by hsubramanianaks** [comment]
@yehia2amer Yes you are welcome to raise a PR, it's a good idea, our team will validate and test them. Thank you.

**Comment by markphillips100** [comment]
In case it was missed, if you are going to use an env variable to override the registry you can already specify overrides for both images to be downloaded.  Use `docker tag` if you need to rename the images.

The env vars BRIDGE_DEVHOSTIMAGENAME and BRIDGE_RESTORATIONJOBIMAGENAME will override the full image name and tag.

**Comment by hsubramanianaks** [comment]
Thanks @markphillips100 for the workaround. @yehia2amer actually you can try using this env variables for dev host, restoration and routing manager images to read them via your private registry. while pushing them you need to build user the Dockerfile and tag them using your private registry name / lpkremoteagent:version and provide this a value to the env variables ex: BRIDGE_DEVHOSTIMAGENAME=yourprivateregistry.io/lpkremoteagent:v1. if this work around helps your use case. please confirm we will close this issue. Thanks.

![image](https://user-images.githubusercontent.com/105889062/204846666-cb8a7480-1bae-4ee9-a71c-44b1d377940d.png)

**Comment by elenavillamil** [comment]
Closing this since per @hsubramanianaks bridge already has a mechanism to override the images, including registry. @yehia2amer please feel free to re-open if above doesn't work or you run into issue.
