### ISSUE TITLE
How can I configure Bridge to NOT forward certain services' ports?

### ISSUE THREAD

**Issue by ptixed** [Azure/Bridge-To-Kubernetes#89]
Hello,

How can I configure Bridge to NOT forward certain services' ports?

I have a smb server on my cluster and I am trying to debug another app that does not depend on it. Bridge tries to allocate port 445 on my local machine and errors out because this port is already in use (I'm on windows, port 445 is in use by default). How can I tell the Bridge to just ignore the smb service and don't perform any forwards?

**Comment by elenavillamil** [comment]
Hi @ptixed, this is not supported today. As a temporary workaround you can change the port your Kubernetes service uses. I have marked this as "Feature Request" and we will investigate as a team if it is possible to add this feature. Thank you.

**Comment by elenavillamil** [comment]
Closing since this has been address with 02/16 release.
